### ISSUE TITLE
Functional tests are stupidly slow to run on OS X

### ISSUE THREAD

**Issue by Zensavona** [theintern/intern#315]
this issue I'm encountering has already been pretty documented/discussed [on StackOverflow](http://stackoverflow.com/questions/26213191/local-functional-tests-start-after-more-then-1-minute) (basically there are some feature checks with selenium which take a really really long time, it looks like something to do with random number generation?) but there is no solution and I can't see any issue about it, so here's my log anyway:

Selenium Server:

```
12:34:52.455 INFO - Executing: [new session: Capabilities [{idle-timeout=60, platform=MAC, browserName=chrome, selenium-version=2.41.0, name=tests/intern, version=39}]])
12:34:52.457 INFO - Creating a new session for Capabilities [{idle-timeout=60, platform=MAC, browserName=chrome, selenium-version=2.41.0, name=tests/intern, version=39}]
Starting ChromeDriver (v2.9.248307) on port 29825
12:34:55.065 INFO - Done: [new session: Capabilities [{idle-timeout=60, platform=MAC, browserName=chrome, selenium-version=2.41.0, name=tests/intern, version=39}]]
12:34:55.098 INFO - Executing: [get: about:blank])
12:34:55.569 INFO - Done: [get: about:blank]
12:34:55.587 INFO - Executing: [get location context])
12:34:55.587 INFO - Executing: [take screenshot])
12:34:55.587 INFO - Executing: [get local storage size])
12:34:55.599 INFO - Executing: [execute async script: arguments[0](true);, []])
12:34:55.613 INFO - Executing: [doubleclick: no args])
12:34:58.466 INFO - Done: [take screenshot]
12:34:58.469 INFO - Executing: [Long press: null])
12:34:58.486 INFO - Done: [execute async script: arguments[0](true);, []]
12:34:58.488 INFO - Executing: [get window size])
12:34:58.581 INFO - Done: [doubleclick: no args]
12:34:58.581 WARN - Exception thrown
java.lang.UnsupportedOperationException: Underlying driver does not implement advanced user interactions yet.
    at org.openqa.selenium.support.events.EventFiringWebDriver.getTouch(EventFiringWebDriver.java:311)
    at org.openqa.selenium.remote.server.handler.interactions.touch.LongPressOnElement.call(LongPressOnElement.java:40)
    at org.openqa.selenium.remote.server.handler.interactions.touch.LongPressOnElement.call(LongPressOnElement.java:1)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:168)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
12:34:58.582 WARN - Exception: Underlying driver does not implement advanced user interactions yet.
12:34:58.594 INFO - Done: [get window size]
12:34:58.606 INFO - Executing: [set window size])
12:34:58.722 INFO - Done: [set window size]
12:35:05.784 WARN - Exception thrown
org.openqa.selenium.WebDriverException: unknown error: Location must be set before it can be retrieved
  (Session info: chrome=39.0.2171.71)
  (Driver info: chromedriver=2.9.248307,platform=Mac OS X 10.10.0 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 5 milliseconds
Build info: version: '2.44.0', revision: '76d78cf', time: '2014-10-23 20:02:37'
System info: host: 'MacBook-Air.local', ip: '127.0.0.1', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10', java.version: '1.7.0_55'
Session ID: 3a28f8d89820fddc67e5bdc7d80dce9e
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{platform=MAC, acceptSslCerts=true, javascriptEnabled=true, browserName=chrome, chrome={userDataDir=/var/folders/l_/_c6vfgld6n17j9qf5r98qyl40000gn/T/.org.chromium.Chromium.jqtvFi}, rotatable=false, locationContextEnabled=true, version=39.0.2171.71, takesHeapSnapshot=true, cssSelectorsEnabled=true, databaseEnabled=false, handlesAlerts=true, browserConnectionEnabled=false, webStorageEnabled=true, nativeEvents=true, applicationCacheEnabled=false, takesScreenshot=true}]
    at sun.reflect.GeneratedConstructorAccessor17.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
    at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
    at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:614)
    at org.openqa.selenium.remote.RemoteExecuteMethod.execute(RemoteExecuteMethod.java:32)
    at org.openqa.selenium.remote.html5.RemoteLocationContext.location(RemoteLocationContext.java:38)
    at org.openqa.selenium.chrome.ChromeDriver.location(ChromeDriver.java:195)
    at org.openqa.selenium.remote.server.handler.html5.GetLocationContext.call(GetLocationContext.java:31)
    at org.openqa.selenium.remote.server.handler.html5.GetLocationContext.call(GetLocationContext.java:1)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:168)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
12:35:21.000 WARN - Exception thrown
org.openqa.selenium.WebDriverException: unknown error: Runtime.evaluate threw exception: DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
  (Session info: chrome=39.0.2171.71)
  (Driver info: chromedriver=2.9.248307,platform=Mac OS X 10.10.0 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 10 milliseconds
Build info: version: '2.44.0', revision: '76d78cf', time: '2014-10-23 20:02:37'
System info: host: 'MacBook-Air.local', ip: '127.0.0.1', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10', java.version: '1.7.0_55'
Session ID: 3a28f8d89820fddc67e5bdc7d80dce9e
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{platform=MAC, acceptSslCerts=true, javascriptEnabled=true, browserName=chrome, chrome={userDataDir=/var/folders/l_/_c6vfgld6n17j9qf5r98qyl40000gn/T/.org.chromium.Chromium.jqtvFi}, rotatable=false, locationContextEnabled=true, version=39.0.2171.71, takesHeapSnapshot=true, cssSelectorsEnabled=true, databaseEnabled=false, handlesAlerts=true, browserConnectionEnabled=false, webStorageEnabled=true, nativeEvents=true, applicationCacheEnabled=false, takesScreenshot=true}]
    at sun.reflect.GeneratedConstructorAccessor17.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
    at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
    at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:614)
    at org.openqa.selenium.remote.RemoteExecuteMethod.execute(RemoteExecuteMethod.java:32)
    at org.openqa.selenium.remote.html5.RemoteLocalStorage.size(RemoteLocalStorage.java:72)
    at org.openqa.selenium.remote.server.handler.html5.GetLocalStorageSize.call(GetLocalStorageSize.java:30)
    at org.openqa.selenium.remote.server.handler.html5.GetLocalStorageSize.call(GetLocalStorageSize.java:1)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:168)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
12:35:36.300 WARN - Exception: unknown error: Location must be set before it can be retrieved
  (Session info: chrome=39.0.2171.71)
  (Driver info: chromedriver=2.9.248307,platform=Mac OS X 10.10.0 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 5 milliseconds
Build info: version: '2.44.0', revision: '76d78cf', time: '2014-10-23 20:02:37'
System info: host: 'MacBook-Air.local', ip: '127.0.0.1', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10', java.version: '1.7.0_55'
Session ID: 3a28f8d89820fddc67e5bdc7d80dce9e
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{platform=MAC, acceptSslCerts=true, javascriptEnabled=true, browserName=chrome, chrome={userDataDir=/var/folders/l_/_c6vfgld6n17j9qf5r98qyl40000gn/T/.org.chromium.Chromium.jqtvFi}, rotatable=false, locationContextEnabled=true, version=39.0.2171.71, takesHeapSnapshot=true, cssSelectorsEnabled=true, databaseEnabled=false, handlesAlerts=true, browserConnectionEnabled=false, webStorageEnabled=true, nativeEvents=true, applicationCacheEnabled=false, takesScreenshot=true}]
12:36:01.782 WARN - Exception: unknown error: Runtime.evaluate threw exception: DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
  (Session info: chrome=39.0.2171.71)
  (Driver info: chromedriver=2.9.248307,platform=Mac OS X 10.10.0 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 10 milliseconds
Build info: version: '2.44.0', revision: '76d78cf', time: '2014-10-23 20:02:37'
System info: host: 'MacBook-Air.local', ip: '127.0.0.1', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10', java.version: '1.7.0_55'
Session ID: 3a28f8d89820fddc67e5bdc7d80dce9e
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{platform=MAC, acceptSslCerts=true, javascriptEnabled=true, browserName=chrome, chrome={userDataDir=/var/folders/l_/_c6vfgld6n17j9qf5r98qyl40000gn/T/.org.chromium.Chromium.jqtvFi}, rotatable=false, locationContextEnabled=true, version=39.0.2171.71, takesHeapSnapshot=true, cssSelectorsEnabled=true, databaseEnabled=false, handlesAlerts=true, browserConnectionEnabled=false, webStorageEnabled=true, nativeEvents=true, applicationCacheEnabled=false, takesScreenshot=true}]
12:36:57.744 INFO - Executing: [get: data:text/html;charset=utf-8,%3C!DOCTYPE%20html%3E%3Ctitle%3Ea%3C%2Ftitle%3E])
12:36:57.783 INFO - Done: [get: data:text/html;charset=utf-8,%3C!DOCTYPE%20html%3E%3Ctitle%3Ea%3C%2Ftitle%3E]
12:36:57.796 INFO - Executing: [get title])
12:36:57.813 INFO - Done: [get title]
12:36:57.819 INFO - Executing: [get: data:text/html;charset=utf-8,%3C!DOCTYPE%20html%3E%3Cstyle%3E%23a%7Bwidth%3A8px%3Bheight%3A8px%3B-ms-transform%3Ascale(0.5)%3B-moz-transform%3Ascale(0.5)%3B-webkit-transform%3Ascale(0.5)%3Btransform%3Ascale(0.5)%3B%7D%3C%2Fstyle%3E%3Cdiv%20id%3D%22a%22%3E%3C%2Fdiv%3E])
12:36:57.857 INFO - Done: [get: data:text/html;charset=utf-8,%3C!DOCTYPE%20html%3E%3Cstyle%3E%23a%7Bwidth%3A8px%3Bheight%3A8px%3B-ms-transform%3Ascale(0.5)%3B-moz-transform%3Ascale(0.5)%3B-webkit-transform%3Ascale(0.5)%3Btransform%3Ascale(0.5)%3B%7D%3C%2Fstyle%3E%3Cdiv%20id%3D%22a%22%3E%3C%2Fdiv%3E]
12:36:57.864 INFO - Executing: [execute script: return (function () {
                        var bbox = document.getElementById('a').getBoundingClientRect();
                        return bbox.right - bbox.left === 4;
                    }).apply(this, arguments);, []])
12:36:57.885 INFO - Done: [execute script: return (function () {
                        var bbox = document.getElementById('a').getBoundingClientRect();
                        return bbox.right - bbox.left === 4;
                    }).apply(this, arguments);, []]
12:36:57.892 INFO - Executing: [get: about:blank])
12:36:57.946 INFO - Done: [get: about:blank]
12:36:57.962 INFO - Executing: [fetching available log types])
12:36:57.963 INFO - Executing: [find element: By.tagName: html])
12:36:57.963 INFO - Executing: [find element: By.tagName: html])
12:36:57.967 INFO - Done: [fetching available log types]
12:36:58.011 INFO - Done: [find element: By.tagName: html]
12:36:58.018 INFO - Executing: [tag name: 0 [[ChromeDriver: chrome on MAC (3a28f8d89820fddc67e5bdc7d80dce9e)] -> tag name: html]])
12:36:58.023 INFO - Done: [find element: By.tagName: html]
12:36:58.032 INFO - Executing: [get element attribute: 0 [[ChromeDriver: chrome on MAC (3a28f8d89820fddc67e5bdc7d80dce9e)] -> tag name: html], nonexisting])
12:36:58.036 INFO - Done: [tag name: 0 [[ChromeDriver: chrome on MAC (3a28f8d89820fddc67e5bdc7d80dce9e)] -> tag name: html]]
12:36:58.052 INFO - Done: [get element attribute: 0 [[ChromeDriver: chrome on MAC (3a28f8d89820fddc67e5bdc7d80dce9e)] -> tag name: html], nonexisting]
12:36:58.059 INFO - Executing: [get: data:text/html;charset=utf-8,%3C!DOCTYPE%20html%3E%3Cdiv%20id%3D%22a%22%3E%3C%2Fdiv%3E])
12:36:58.095 INFO - Done: [get: data:text/html;charset=utf-8,%3C!DOCTYPE%20html%3E%3Cdiv%20id%3D%22a%22%3E%3C%2Fdiv%3E]
12:36:58.101 INFO - Executing: [execute script: return document.getElementById("a");, []])
12:36:58.109 INFO - Done: [execute script: return document.getElementById("a");, []]
12:36:58.114 INFO - Executing: [tag name: 1 [org.openqa.selenium.remote.RemoteWebElement@72e5f539 -> unknown locator]])
12:36:58.119 INFO - Done: [tag name: 1 [org.openqa.selenium.remote.RemoteWebElement@72e5f539 -> unknown locator]]
12:36:58.125 INFO - Executing: [get: data:text/html;charset=utf-8,%3C!DOCTYPE%20html%3E%3Cdiv%20id%3D%22a%22%20style%3D%22opacity%3A%20.1%3B%22%3Ea%3C%2Fdiv%3E])
12:36:58.160 INFO - Done: [get: data:text/html;charset=utf-8,%3C!DOCTYPE%20html%3E%3Cdiv%20id%3D%22a%22%20style%3D%22opacity%3A%20.1%3B%22%3Ea%3C%2Fdiv%3E]
12:36:58.165 INFO - Executing: [execute script: var o = document.getElementById("a").style.opacity; return o && o.charAt(0) === "0";, []])
12:36:58.175 INFO - Done: [execute script: var o = document.getElementById("a").style.opacity; return o && o.charAt(0) === "0";, []]
12:36:58.186 INFO - Executing: [execute script: document.getElementById("a").style.opacity = "0";, []])
12:36:58.192 INFO - Done: [execute script: document.getElementById("a").style.opacity = "0";, []]
12:36:58.200 INFO - Executing: [find element: By.id: a])
12:36:58.220 INFO - Done: [find element: By.id: a]
12:36:58.225 INFO - Executing: [is displayed: 2 [[ChromeDriver: chrome on MAC (3a28f8d89820fddc67e5bdc7d80dce9e)] -> id: a]])
12:36:58.244 INFO - Done: [is displayed: 2 [[ChromeDriver: chrome on MAC (3a28f8d89820fddc67e5bdc7d80dce9e)] -> id: a]]
12:36:58.250 INFO - Executing: [get: data:text/html;charset=utf-8,%3C!DOCTYPE%20html%3E%3Cdiv%20id%3D%22a%22%20style%3D%22left%3A%200%3B%20position%3A%20absolute%3B%20top%3A%20-1000px%3B%22%3Ea%3C%2Fdiv%3E])
12:36:58.288 INFO - Done: [get: data:text/html;charset=utf-8,%3C!DOCTYPE%20html%3E%3Cdiv%20id%3D%22a%22%20style%3D%22left%3A%200%3B%20position%3A%20absolute%3B%20top%3A%20-1000px%3B%22%3Ea%3C%2Fdiv%3E]
12:36:58.297 INFO - Executing: [find element: By.id: a])
12:36:58.309 INFO - Done: [find element: By.id: a]
12:36:58.314 INFO - Executing: [is displayed: 3 [[ChromeDriver: chrome on MAC (3a28f8d89820fddc67e5bdc7d80dce9e)] -> id: a]])
12:36:58.332 INFO - Done: [is displayed: 3 [[ChromeDriver: chrome on MAC (3a28f8d89820fddc67e5bdc7d80dce9e)] -> id: a]]
12:36:58.350 INFO - Executing: [get: data:text/html;charset=utf-8,%3C!DOCTYPE%20html%3E%3Cform%20method%3D%22get%22%20action%3D%22about%3Ablank%22%3E%3Cinput%20id%3D%22a%22%20type%3D%22submit%22%20name%3D%22a%22%20value%3D%22a%22%3E%3C%2Fform%3E])
12:36:58.397 INFO - Done: [get: data:text/html;charset=utf-8,%3C!DOCTYPE%20html%3E%3Cform%20method%3D%22get%22%20action%3D%22about%3Ablank%22%3E%3Cinput%20id%3D%22a%22%20type%3D%22submit%22%20name%3D%22a%22%20value%3D%22a%22%3E%3C%2Fform%3E]
12:36:58.403 INFO - Executing: [find element: By.id: a])
12:36:58.415 INFO - Done: [find element: By.id: a]
12:36:58.420 INFO - Executing: [submit: 4 [[ChromeDriver: chrome on MAC (3a28f8d89820fddc67e5bdc7d80dce9e)] -> id: a]])
12:36:58.497 INFO - Done: [submit: 4 [[ChromeDriver: chrome on MAC (3a28f8d89820fddc67e5bdc7d80dce9e)] -> id: a]]
12:36:58.503 INFO - Executing: [get current url])
12:36:58.511 INFO - Done: [get current url]
12:36:58.516 INFO - Executing: [get: data:text/html;charset=utf-8,%3C!DOCTYPE%20html%3E%3Cdiv%20id%3D%22a%22%20style%3D%22margin%3A%203000px%3B%22%3E%3C%2Fdiv%3E])
12:36:58.550 INFO - Done: [get: data:text/html;charset=utf-8,%3C!DOCTYPE%20html%3E%3Cdiv%20id%3D%22a%22%20style%3D%22margin%3A%203000px%3B%22%3E%3C%2Fdiv%3E]
12:36:58.555 INFO - Executing: [find element: By.id: a])
12:36:58.566 INFO - Done: [find element: By.id: a]
12:36:58.571 INFO - Executing: [get location: 5 [[ChromeDriver: chrome on MAC (3a28f8d89820fddc67e5bdc7d80dce9e)] -> id: a]])
12:36:58.578 INFO - Done: [get location: 5 [[ChromeDriver: chrome on MAC (3a28f8d89820fddc67e5bdc7d80dce9e)] -> id: a]]
12:36:58.583 INFO - Executing: [get: about:blank?1])
12:36:59.263 INFO - Done: [get: about:blank?1]
12:36:59.274 INFO - Executing: [refresh])
12:36:59.304 INFO - Done: [refresh]
12:36:59.317 INFO - Executing: [get: data:text/html;charset=utf-8,%3C!DOCTYPE%20html%3E%3Cscript%3Ecounter%20%3D%200%3B%20var%20d%20%3D%20document%3B%20d.onclick%20%3D%20d.onmousedown%20%3D%20d.onmouseup%20%3D%20function%20()%20%7B%20counter%2B%2B%3B%20%7D%3B%3C%2Fscript%3E])
12:36:59.911 INFO - Done: [get: data:text/html;charset=utf-8,%3C!DOCTYPE%20html%3E%3Cscript%3Ecounter%20%3D%200%3B%20var%20d%20%3D%20document%3B%20d.onclick%20%3D%20d.onmousedown%20%3D%20d.onmouseup%20%3D%20function%20()%20%7B%20counter%2B%2B%3B%20%7D%3B%3C%2Fscript%3E]
12:36:59.917 INFO - Executing: [find element: By.tagName: html])
12:36:59.953 INFO - Done: [find element: By.tagName: html]
12:36:59.961 INFO - Executing: [mousemove: 6 false])
12:36:59.987 INFO - Done: [mousemove: 6 false]
12:37:00.097 INFO - Executing: [doubleclick: no args])
12:37:00.161 INFO - Done: [doubleclick: no args]
12:37:00.168 INFO - Executing: [execute script: return counter;, []])
12:37:00.175 INFO - Done: [execute script: return counter;, []]
12:37:00.182 INFO - Executing: [get: data:text/html;charset=utf-8,%3C!DOCTYPE%20html%3E%3Cstyle%3E%23a%7Bwidth%3A8px%3Bheight%3A8px%3B-ms-transform%3Ascale(0.5)%3B-moz-transform%3Ascale(0.5)%3B-webkit-transform%3Ascale(0.5)%3Btransform%3Ascale(0.5)%3B%7D%3C%2Fstyle%3E%3Cdiv%20id%3D%22a%22%3E%3C%2Fdiv%3E])
12:37:00.231 INFO - Done: [get: data:text/html;charset=utf-8,%3C!DOCTYPE%20html%3E%3Cstyle%3E%23a%7Bwidth%3A8px%3Bheight%3A8px%3B-ms-transform%3Ascale(0.5)%3B-moz-transform%3Ascale(0.5)%3B-webkit-transform%3Ascale(0.5)%3Btransform%3Ascale(0.5)%3B%7D%3C%2Fstyle%3E%3Cdiv%20id%3D%22a%22%3E%3C%2Fdiv%3E]
12:37:00.239 INFO - Executing: [execute script: return document.getElementById("a");, []])
12:37:00.251 INFO - Done: [execute script: return document.getElementById("a");, []]
12:37:00.257 INFO - Executing: [get element size: 7 [org.openqa.selenium.remote.RemoteWebElement@6109e01a -> unknown locator]])
12:37:00.267 INFO - Done: [get element size: 7 [org.openqa.selenium.remote.RemoteWebElement@6109e01a -> unknown locator]]
12:37:00.274 INFO - Executing: [get: about:blank])
12:37:00.373 INFO - Done: [get: about:blank]
12:37:00.390 INFO - Executing: [get current url])
12:37:00.391 INFO - Executing: [execute script: return (function getCoverageData() {
        /*global __internCoverage:false */
        return typeof __internCoverage !== 'undefined' && JSON.stringify(__internCoverage);
    }).apply(this, arguments);, []])
12:37:00.398 INFO - Done: [get current url]
12:37:00.406 INFO - Done: [execute script: return (function getCoverageData() {
        /*global __internCoverage:false */
        return typeof __internCoverage !== 'undefined' && JSON.stringify(__internCoverage);
    }).apply(this, arguments);, []]
12:37:00.414 INFO - Executing: [get: http://localhost:9000/__intern/client.html?config=tests%2Fintern&reporters=webdriver&functionalSuites=tests%2Ffunctional%2Findex&baseUrl=%2F&sessionId=4dd529c0-83c0-4da6-9e84-fbae7d6339d5])
12:37:01.050 INFO - Done: [get: http://localhost:9000/__intern/client.html?config=tests%2Fintern&reporters=webdriver&functionalSuites=tests%2Ffunctional%2Findex&baseUrl=%2F&sessionId=4dd529c0-83c0-4da6-9e84-fbae7d6339d5]
12:37:01.063 INFO - Executing: [execute script: return (function getCoverageData() {
        /*global __internCoverage:false */
        return typeof __internCoverage !== 'undefined' && JSON.stringify(__internCoverage);
    }).apply(this, arguments);, []])
12:37:01.072 INFO - Done: [execute script: return (function getCoverageData() {
        /*global __internCoverage:false */
        return typeof __internCoverage !== 'undefined' && JSON.stringify(__internCoverage);
    }).apply(this, arguments);, []]
12:37:01.080 INFO - Executing: [get: about:blank])
12:37:01.148 INFO - Done: [get: about:blank]
12:37:01.172 INFO - Executing: [execute script: return (function getCoverageData() {
        /*global __internCoverage:false */
        return typeof __internCoverage !== 'undefined' && JSON.stringify(__internCoverage);
    }).apply(this, arguments);, []])
12:37:01.203 INFO - Done: [execute script: return (function getCoverageData() {
        /*global __internCoverage:false */
        return typeof __internCoverage !== 'undefined' && JSON.stringify(__internCoverage);
    }).apply(this, arguments);, []]
12:37:01.214 INFO - Executing: [get: http://127.0.0.1:8080/web-admin/public/#/])
12:37:01.788 INFO - Done: [get: http://127.0.0.1:8080/web-admin/public/#/]
12:37:01.798 INFO - Executing: [implicit wait: 5000])
12:37:01.804 INFO - Done: [implicit wait: 5000]
12:37:01.816 INFO - Executing: [find element: By.selector: form#login-form])
12:37:02.531 INFO - Done: [find element: By.selector: form#login-form]
12:37:02.541 INFO - Executing: [find child element: 8 [[ChromeDriver: chrome on MAC (3a28f8d89820fddc67e5bdc7d80dce9e)] -> css selector: form#login-form], By.id: login-button])
12:37:02.571 INFO - Done: [find child element: 8 [[ChromeDriver: chrome on MAC (3a28f8d89820fddc67e5bdc7d80dce9e)] -> css selector: form#login-form], By.id: login-button]
12:37:02.578 INFO - Executing: [click: 9 [[[[ChromeDriver: chrome on MAC (3a28f8d89820fddc67e5bdc7d80dce9e)] -> css selector: form#login-form]] -> id: login-button]])
12:37:02.667 INFO - Done: [click: 9 [[[[ChromeDriver: chrome on MAC (3a28f8d89820fddc67e5bdc7d80dce9e)] -> css selector: form#login-form]] -> id: login-button]]
12:37:02.691 INFO - Executing: [find child element: 8 [[ChromeDriver: chrome on MAC (3a28f8d89820fddc67e5bdc7d80dce9e)] -> css selector: form#login-form], By.id: login-error])
12:37:02.718 INFO - Done: [find child element: 8 [[ChromeDriver: chrome on MAC (3a28f8d89820fddc67e5bdc7d80dce9e)] -> css selector: form#login-form], By.id: login-error]
12:37:02.724 INFO - Executing: [get text: 10 [[[[ChromeDriver: chrome on MAC (3a28f8d89820fddc67e5bdc7d80dce9e)] -> css selector: form#login-form]] -> id: login-error]])
12:37:02.757 INFO - Done: [get text: 10 [[[[ChromeDriver: chrome on MAC (3a28f8d89820fddc67e5bdc7d80dce9e)] -> css selector: form#login-form]] -> id: login-error]]
12:37:02.767 INFO - Executing: [execute script: return (function getCoverageData() {
        /*global __internCoverage:false */
        return typeof __internCoverage !== 'undefined' && JSON.stringify(__internCoverage);
    }).apply(this, arguments);, []])
12:37:02.773 INFO - Done: [execute script: return (function getCoverageData() {
        /*global __internCoverage:false */
        return typeof __internCoverage !== 'undefined' && JSON.stringify(__internCoverage);
    }).apply(this, arguments);, []]
12:37:02.777 INFO - Executing: [delete session: 4dd529c0-83c0-4da6-9e84-fbae7d6339d5])
12:37:03.404 INFO - Done: [delete session: 4dd529c0-83c0-4da6-9e84-fbae7d6339d5]
```

Intern:

```
node_modules/.bin/intern-runner config=tests/intern
Listening on 0.0.0.0:9000
Starting tunnel...
Initialised chrome 39.0.2171.71 on MAC
No unit test coverage for chrome 39.0.2171.71 on MAC
chrome 39.0.2171.71 on MAC: 0/1 tests failed

TOTAL: tested 1 platforms, 0/1 tests failed
```

**Comment by davidofwatkins** [comment]
@Zensavona I was having this issue as well for awhile. It was finally resolved by reverting to JDK 1.8.0_45 (see [here](http://stackoverflow.com/a/40291877/477632)).
