### ISSUE TITLE
wrong line numbers

### ISSUE THREAD

**Issue by bartoszkaczorek** [theintern/intern#332]
Hi,
I am running functional tests using Intern and I experience that it prints wrong line numbers when an error occurs in the tests.

Here's my environment details:
Intern version: 2.2.2
Reporters used: ['runner']
platform: Windows

Thanks,
Bartosz

**Comment by csnover** [comment]
Thank you for the report. In order to take any action, could you please provide a test case that demonstrates this issue?

**Comment by bartoszkaczorek** [comment]
Hi,

Here's the example functional test (21 lines total):

```javascript
 define([ 'intern!bdd', 'intern/chai!expect' ], function(bdd, expect) {
	"use strict";

	bdd.describe('Example Test', function() {

		bdd.it('Hello World', function() {

			this.timeout = 30000;

			return this.remote

			.get('http://www.google.com')

			.findById('hplogo_non_existing_element').end();

		});

	});

});
```
Here's the output after running the test:
```
Listening on 0.0.0.0:9000
Starting tunnel...
Initialised chrome 39.0.2171.95 on XP
Test main - Example Test - Hello World FAILED on chrome 39.0.2171.95 on XP:
NoSuchElement: [POST http://localhost:4444/wd/hub/session/9265b7f5-75de-4086-8ee6-7514a2fe886a/element / {"using":"id","value":"hplogo_non_existing_element"}] no such element
  (Session info: chrome=39.0.2171.95)
  (Driver info: chromedriver=2.9.248315,platform=Windows NT 6.1 SP1 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 62 milliseconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '2.43.1', revision: '5163bce', time: '2014-09-10 16:27:33'
System info: host: 'VDDP03P-5CFEDE2', ip: '10.172.12.225', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.6.0_26'
Session ID: cc206c359ebc90048271c5c58df4bf28
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{platform=XP, acceptSslCerts=true, javascriptEnabled=true, browserName=chrome, chrome={userDataDir=****},
rotatable=false, locationContextEnabled=true, version=39.0.2171.95, takesHeapSnapshot=true, cssSelectorsEnabled=true, databaseEnabled=false, handlesAlerts=true, browserConnectionEnabled=false, nativeEvents=true, webStorageEnabled=true, applicationCacheEnabled=false, takesScreenshot=true}]
  at Server._post  <node_modules\intern\node_modules\leadfoot\Server.js:68:9>
  at ProxiedSession._post  <node_modules\intern\node_modules\leadfoot\Session.js:57:30>
  at ProxiedSession.Session.find  <node_modules\intern\node_modules\leadfoot\Session.js:1053:15>
  at CompatCommand.<anonymous>  <node_modules\intern\node_modules\leadfoot\Command.js:41:36>
  at <node_modules\intern\node_modules\leadfoot\node_modules\dojo\Promise.js:235:37>
  at runCallbacks  <node_modules\intern\node_modules\leadfoot\node_modules\dojo\Promise.js:11:18>
  at <node_modules\intern\node_modules\leadfoot\node_modules\dojo\Promise.js:188:17>
  at Object.run [as _onImmediate]  <node_modules\intern\node_modules\leadfoot\node_modules\dojo\Promise.js:131:29>
  at processImmediate [as _immediateCallback]  <timers.js:330:15>
  at new CompatCommand  <node_modules\intern\runner.js:213:14>
  at CompatCommand.find  <node_modules\intern\node_modules\leadfoot\Command.js:22:10>
  at <CompatCommand.prototype.(anonymous function) [as findById] (****\node_modules\leadfoot\lib\strategies.js:24:16)>
  at Test.test  <exampleTests\pocWrongLines\exampleTests.js:25:61>
  at Test.run  <node_modules\intern\lib\Test.js:207:31>
  at <node_modules\intern\lib\Suite.js:237:13>
  at signalListener  <node_modules\intern\node_modules\dojo\Deferred.js:37:21>
  at Promise.then.promise.then  <node_modules\intern\node_modules\dojo\Deferred.js:258:5>
  at runTest  <node_modules\intern\lib\Suite.js:236:46>
  at <node_modules\intern\lib\Suite.js:249:7>
  at new CompatCommand  <node_modules\intern\runner.js:213:14>
  at CompatCommand.Command.end  <node_modules\intern\node_modules\leadfoot\Command.js:475:10>
  at Test.test  <exampleTests\pocWrongLines\exampleTests.js:25:101>
  at Test.run  <node_modules\intern\lib\Test.js:207:31>
  at <node_modules\intern\lib\Suite.js:237:13>
  at signalListener  <node_modules\intern\node_modules\dojo\Deferred.js:37:21>
  at Promise.then.promise.then  <node_modules\intern\node_modules\dojo\Deferred.js:258:5>
  at runTest  <node_modules\intern\lib\Suite.js:236:46>
  at <node_modules\intern\lib\Suite.js:249:7>
  at process._tickCallback  <node.js:415:13>
```
As you can see it is pointing to line 25 in exampleTests.js but it has only 21 lines:
` at Test.test  <exampleTests\pocWrongLines\exampleTests.js:25:101>`

Thanks,
Bartosz

**Comment by csnover** [comment]
My guess is that you have not excluded your tests from code coverage instrumentation so it is point to line numbers post-instrumentation. https://github.com/theintern/intern/pull/339 might fix this, can you try applying it?

**Comment by bartoszkaczorek** [comment]
Yes I was not excluding the tests from code coverage instrumentation, excluding them helped to fix that issue.

**Comment by csnover** [comment]
I’ve verified the test case you’ve provided works correctly in Intern 3.
