### ISSUE TITLE
When running functional tests on Fedora, Intern cannot find module 'digdug/nullTunnel'

### ISSUE THREAD

**Issue by Zensavona** [theintern/intern#335]
Hi guys,

So I'm running some functional tests (just chromedriver for now)

````
Running "exec:startselenium" (exec) task

Running "intern:runner" (intern) task

module.js:340
    throw err;
          ^
Error: Cannot find module 'digdug/nullTunnel'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.load (/home/zensavona/softwaredev/projects/haze/t3/t3-web/web-admin/src/main/node_modules/intern/node_modules/dojo/node.js:53:14)
    at injectPlugin (/home/zensavona/softwaredev/projects/haze/t3/t3-web/web-admin/src/main/node_modules/intern/node_modules/dojo/dojo.js:608:12)
    at injectModule (/home/zensavona/softwaredev/projects/haze/t3/t3-web/web-admin/src/main/node_modules/intern/node_modules/dojo/dojo.js:632:5)
    at Array.forEach (native)
    at forEach (/home/zensavona/softwaredev/projects/haze/t3/t3-web/web-admin/src/main/node_modules/intern/node_modules/dojo/dojo.js:220:19)
    at /home/zensavona/softwaredev/projects/haze/t3/t3-web/web-admin/src/main/node_modules/intern/node_modules/dojo/dojo.js:272:6
````

is this an issue of it not being able to find or communicate with chromedriver and/or selenium? or something completely different.

FWIW it works fine on my mac.

**Comment by csnover** [comment]
The tunnel name is `NullTunnel`, not `nullTunnel`. The only reason why it happens to work on Mac OS is because that filesystem is case-insensitive by default.

**Comment by Zensavona** [comment]
:ok_hand: thanks so much
