### ISSUE TITLE
TypeError: Cannot call method 'indexOf' of null

### ISSUE THREAD

**Issue by Zensavona** [theintern/intern#336]
Hi guys, I'm having an issue running my functional tests on Fedora (they run fine on OS X), I think it might be chromedriver/selenium related?

Any insight would be great.

Here's my output:

````
Running "exec:startselenium" (exec) task

Running "intern:runner" (intern) task
Listening on 0.0.0.0:9000
Starting tunnel...
TypeError: Cannot call method 'indexOf' of null
  at handleResponse  <node_modules/intern/node_modules/leadfoot/Server.js:148:26>
  at <node_modules/intern/node_modules/leadfoot/node_modules/dojo/Promise.js:235:37>
  at runCallbacks  <node_modules/intern/node_modules/leadfoot/node_modules/dojo/Promise.js:11:18>
  at <node_modules/intern/node_modules/leadfoot/node_modules/dojo/Promise.js:188:17>
  at Object.run [as _onImmediate]  <node_modules/intern/node_modules/leadfoot/node_modules/dojo/Promise.js:131:29>
  at processImmediate [as _immediateCallback]  <timers.js:345:15>

----------------|-----------|-----------|-----------|-----------|
File            |   % Stmts |% Branches |   % Funcs |   % Lines |
----------------|-----------|-----------|-----------|-----------|
   chance/      |     40.29 |     20.14 |     27.82 |      40.7 |
      chance.js |     40.29 |     20.14 |     27.82 |      40.7 |
----------------|-----------|-----------|-----------|-----------|
All files       |     40.29 |     20.14 |     27.82 |      40.7 |
----------------|-----------|-----------|-----------|-----------|

>> TOTAL: tested 0 platforms, 0/0 tests failed; fatal error occurred
````

Here's the output on OS X of exactly the same command/tests:

````
Running "exec:startselenium" (exec) task

Running "intern:runner" (intern) task
Listening on 0.0.0.0:9000
Starting tunnel...
Initialised chrome 39.0.2171.99 on MAC
No unit test coverage for chrome 39.0.2171.99 on MAC
>> chrome 39.0.2171.99 on MAC: 0/5 tests failed

----------------|-----------|-----------|-----------|-----------|
File            |   % Stmts |% Branches |   % Funcs |   % Lines |
----------------|-----------|-----------|-----------|-----------|
   chance/      |     40.29 |     20.14 |     27.82 |      40.7 |
      chance.js |     40.29 |     20.14 |     27.82 |      40.7 |
----------------|-----------|-----------|-----------|-----------|
All files       |     40.29 |     20.14 |     27.82 |      40.7 |
----------------|-----------|-----------|-----------|-----------|

>> TOTAL: tested 1 platforms, 0/5 tests failed

Running "exec:stopselenium" (exec) task
````

Any ideas?

**Comment by kitsonk** [comment]
If you are looking for support, you should ask your questions on StackOverflow instead of here.  This is for once you identify an issue and it would be better to get support on StackOverflow and then if it identifies a defect then to raise it in the proper issue tracker, because even if it is an issue, The Intern uses LeadFoot to integrate and the issue needs to be addressed there.
