### ISSUE TITLE
Strange fails on getCoverageData() when running on BrowserStack

### ISSUE THREAD

**Issue by Zensavona** [theintern/intern#345]
I'm running some functional tests on BrowserStack, which seem to time out in various places when Intern runs what look like coverage data checkers. I'm getting errors which look like this:

````
no such element (Session info: chrome=39.0.2171.65) (Driver info: chromedriver=2.12.301326 (093c7e07b4a916b690e784b0374c7f618f1ea4be),platform=Mac OS X 10.7.5 x86_64) (WARNING: The server did not provide any stacktrace information) Command duration or timeout: 30.06 seconds For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html Build info: version: '2.43.1', revision: '5163bce', time: '2014-09-10 16:27:33' System info: host: 'mac-208-52-180-34.browserstack.com', ip: '208.52.180.34', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.7.5', java.version: '1.6.0_65' Session ID: 680ec3aaa8f996ebb3ea34694908f9d8 Driver info: org.openqa.selenium.chrome.ChromeDriver Capabilities [{platform=MAC, acceptSslCerts=true, javascriptEnabled=true, browserName=chrome, chrome={userDataDir=/var/folders/vh/0qbwlddd68j401bzws3vk6wc0000gq/T/.org.chromium.Chromium.reMw9J}, rotatable=false, locationContextEnabled=true, mobileEmulationEnabled=false, version=39.0.2171.65, takesHeapSnapshot=true, cssSelectorsEnabled=true, databaseEnabled=false, handlesAlerts=true, browserConnectionEnabled=false, nativeEvents=true, webStorageEnabled=true, applicationCacheEnabled=false, takesScreenshot=true}]
````

The interesting part is the code which is causing it:

````
return (function getCoverageData() { /*global __internCoverage:false */ return typeof __internCoverage !== 'undefined' && JSON.stringify(__internCoverage); }).apply(this, arguments);
````

which as far as I can tell is ProxiedSession.js line 8:

````
	function getCoverageData() {
		/*global __internCoverage:false */
		return typeof __internCoverage !== 'undefined' && JSON.stringify(__internCoverage);
	}
````

Any idea why this is happening and is there a way to turn off coverage testing without ripping Intern apart?

# Update

I did a bit more playing around and I've found that even when the aforementioned code runs, it seems to disrupt the test it runs within. Here's an example from BrowserStack:

![BrowserStack](https://cloud.githubusercontent.com/assets/425801/6015153/c31efc46-aba3-11e4-89d4-2e5379ee5588.png)

And the corresponding test code:

````
    'The Service Provider input validation works': function () {
      return this.remote
      .get(require.toUrl(config.url.base))
      .setFindTimeout(30000)
      .findByCssSelector('form#login-form')
        .findById('j_username')
          .click()
          .type(config.data.oscar.email)
        .end()
        .findById('j_password')
          .click()
          .type(config.data.oscar.password)
        .end()
        .findById('login-button')
          .click()
        .end()
      .end()
      .findByLinkText('Service Providers')
        .click()
      .end()
      .findByLinkText('New Service Provider')
        .click()
      .end()
      .findByName('name')
        .click()
        .pressKeys('sp')
      .end()
      .findByName('adminEmail.emailAddress')
        .click()
        .pressKeys('notAnEmailAddress')
      .end()
      .findByName('abn.number')
        .click()
        .pressKeys('666')
      .end()
      .findByName('accountsEmail.emailAddress')
        .click()
        .pressKeys('notAnEmailAddress')
      .end()
      .findByName('supportEmail.emailAddress')
        .click()
        .pressKeys('notAnEmailAddress')
      .end()
      .findByName('accountsPhone.phoneNumber')
        .click()
        .pressKeys('65690')
      .end()
      .findByName('salesPhone.phoneNumber')
        .click()
        .pressKeys('65690')
      .end()
      .findByName('postalAddress.streetNumber')
// ==== This is where the coverage code is interrupting the test (blue part)
        .click()
        .pressKeys('ENTER')
      end()
      .findByName('postalAddress.streetName')
        .click()
        .pressKeys('ENTER')
      end()
      .findByName('postalAddress.city')
        .click()
        .pressKeys('ENTER')
      end()
      .findByName('postalAddress.postcode')
        .click()
        .pressKeys('4')
      end()
      .findByClassName('btn-primary')
        .click()
      .end()
      .findAllByClassName('has-error')
      .then(function (errors) {
        assert.lengthOf(errors, 13);
      });
    },

    'The user can create a new Service Provider': function() {
// === This is where my code resumes running after the coverage code runs (green bit)
     return this.remote
      .get(require.toUrl(config.url.base))
      .setFindTimeout(30000)
      .findByLinkText('Service Providers')
        .click()
      .end()
      .findByLinkText('New Service Provider')
        .click()
      .end()
      .findByName('name')
        .click()
        .pressKeys(config.newSP.original.name)
      .end()
````

And the corresponding Intern output:
````
>> Test main - serviceProviders - The Service Provider input validation works FAILED on chrome 39.0.2171.65 on MAC:
CancelError: Timeout reached on main - serviceProviders - The Service Provider input validation works
Error: Timeout reached on main - serviceProviders - The Service Provider input validation works
  at Error  <anonymous>
  at new ErrorCtor  <node_modules/intern/node_modules/dojo/errors/create.js:13:21>
  at null._onTimeout  <node_modules/intern/lib/Test.js:180:38>
  at Timer.listOnTimeout [as ontimeout]  <timers.js:110:15>
````

Thanks

**Comment by Zensavona** [comment]
Updated OP with more information

**Comment by csnover** [comment]
Hi,

The coverage retrieval is not responsible for your test error, the error “no such element” is coming from the previous find element call. The coverage retrieval occurs after your first test fails and your second test starts, as the first thing the next test does is navigates to a new URL, which is when coverage data is retrieved from the remote client. Since the default test timeout is the same as your find timeout (30s) your test fails with a timeout just a little before the time that the find command would actually time out.

**Comment by Zensavona** [comment]
I see. That makes a lot more sense, I'm looking into it now.

Thanks so much for your response :+1:
