### ISSUE TITLE
Intern self-tests failing on Windows due to path separator differences

### ISSUE THREAD

**Issue by cezarykluczynski** [theintern/intern#405]
Three of Intern's self tests are failing on Windows (fix for the forth one can be cherry-picked from https://github.com/cezarykluczynski/intern/commit/73fdbbcc1fe6a76e37369dd5fb09d3ddc17bcd25).

The main reason seems to be the diffrence in how Windows and Linux reports stack trace in Node. 

Tests are:

tests/unit/lib/reporters/Console.js :: fatalError
tests/unit/lib/utils.js :: source map from instrumentation
tests/unit/lib/util.js :: source map from file

Error messages from Windows 7:

```sh
$ tests/selftest.sh
Running client tests…
FAIL: main - intern/lib/util - .getErrorMessage - source map from instrumentation
AssertionError: expected 'Error: bar\n  at Object.run  <tests\\unit\\data\\lib\\util\\foo.js:124:19>\n  at <tests\\unit\\lib\\util.js:332:29>\n  at <node_modules\\intern\\lib\\Test.js:118:30>\n  at <node_modules\\intern\\lib\\Test.js:134:34>\n  at execModule  <node_modules\\intern\\node_modules\\dojo\\dojo.js:515:54>\n  at <node_modules\\intern\\node_modules\\dojo\\dojo.js:582:7>\n  at guardCheckComplete  <node_modules\\intern\\node_modules\\dojo\\dojo.js:566:4>\n  at checkComplete  <node_modules\\intern\\node_modules\\dojo\\dojo.js:574:27>\n  at onLoadCallback  <node_modules\\intern\\node_modules\\dojo\\dojo.js:656:7>\n  at <node_modules\\intern\\node_modules\\dojo\\dojo.js:761:5>' to include 'util/foo.js:4'
  at Function.assert.include  <node_modules\intern\node_modules\chai\chai.js:2036:57>
  at <tests\unit\lib\util.js:335:32>
  at <node_modules\intern\lib\Test.js:118:30>
  at <node_modules\intern\lib\Test.js:134:34>
  at execModule  <node_modules\intern\node_modules\dojo\dojo.js:515:54>
  at <node_modules\intern\node_modules\dojo\dojo.js:582:7>
  at guardCheckComplete  <node_modules\intern\node_modules\dojo\dojo.js:566:4>
  at checkComplete  <node_modules\intern\node_modules\dojo\dojo.js:574:27>
  at onLoadCallback  <node_modules\intern\node_modules\dojo\dojo.js:656:7>
  at <node_modules\intern\node_modules\dojo\dojo.js:761:5>
FAIL: main - intern/lib/util - .getErrorMessage - source map from file
AssertionError: expected 'Error: foo\n  at Bar.run  <tests\\unit\\data\\lib\\util\\bar.js:27:23>\n  at <tests\\unit\\lib\\util.js:359:29>\n  at <node_modules\\intern\\lib\\Test.js:118:30>\n  at <node_modules\\intern\\lib\\Test.js:134:34>\n  at execModule  <node_modules\\intern\\node_modules\\dojo\\dojo.js:515:54>\n  at <node_modules\\intern\\node_modules\\dojo\\dojo.js:582:7>\n  at guardCheckComplete  <node_modules\\intern\\node_modules\\dojo\\dojo.js:566:4>\n  at checkComplete  <node_modules\\intern\\node_modules\\dojo\\dojo.js:574:27>\n  at onLoadCallback  <node_modules\\intern\\node_modules\\dojo\\dojo.js:656:7>\n  at <node_modules\\intern\\node_modules\\dojo\\dojo.js:761:5>' to match /\bbar.ts:5\b/
  at Function.assert.match  <node_modules\intern\node_modules\chai\chai.js:2048:44>
  at <tests\unit\lib\util.js:362:32>
  at <node_modules\intern\lib\Test.js:118:30>
  at <node_modules\intern\lib\Test.js:134:34>
  at execModule  <node_modules\intern\node_modules\dojo\dojo.js:515:54>
  at <node_modules\intern\node_modules\dojo\dojo.js:582:7>
  at guardCheckComplete  <node_modules\intern\node_modules\dojo\dojo.js:566:4>
  at checkComplete  <node_modules\intern\node_modules\dojo\dojo.js:574:27>
  at onLoadCallback  <node_modules\intern\node_modules\dojo\dojo.js:656:7>
  at <node_modules\intern\node_modules\dojo\dojo.js:761:5>
FAIL: main - intern/lib/reporters/Console - fatalError
AssertionError: Reporter should indicate the location of the error: expected 'FATAL ERROR\nError: Oops\n  at Test.registerSuite.fatalError [as test]  <tests\\unit\\lib\\reporters\\Console.js:101:25>\n  at Test.run  <node_modules\\intern\\lib\\Test.js:207:31>\n  at <node_modules\\intern\\lib\\Suite.js:237:13>\n  at signalListener  <node_modules\\intern\\node_modules\\dojo\\Deferred.js:37:21>\n  at Promise.then.promise.then  <node_modules\\intern\\node_modules\\dojo\\Deferred.js:258:5>\n  at runTest  <node_modules\\intern\\lib\\Suite.js:236:46>\n  at <node_modules\\intern\\lib\\Suite.js:249:7>\n  at process._tickCallback  <node.js:415:13>' to include 'tests/unit/lib/reporters/Console.js:71'
  at Function.assert.include  <node_modules\intern\node_modules\chai\chai.js:2036:57>
  at Test.registerSuite.fatalError [as test]  <tests\unit\lib\reporters\Console.js:118:24>
  at Test.run  <node_modules\intern\lib\Test.js:207:31>
  at <node_modules\intern\lib\Suite.js:237:13>
  at signalListener  <node_modules\intern\node_modules\dojo\Deferred.js:37:21>
  at Promise.then.promise.then  <node_modules\intern\node_modules\dojo\Deferred.js:258:5>
  at runTest  <node_modules\intern\lib\Suite.js:236:46>
  at <node_modules\intern\lib\Suite.js:249:7>
  at process._tickCallback  <node.js:415:13>
```

**Comment by csnover** [comment]
Yep, they are, seems the failures are all related to path separators (as is always the case with anything related to Windows). I’d be happy to accept a patch for this but since we don’t currently have CI for Windows it’s not a very high priority.
