### ISSUE TITLE
Grunt task does not serialize objects

### ISSUE THREAD

**Issue by kitsonk** [theintern/intern#419]
In both 3.0.0-rc.1 and master, using the following configuration:

```js
reporters: [
    { id: 'Console' },
    { id: 'LcovHtml', directory: 'html-test' }
]
```

Results in:

```sh
Error: Failed to load module intern/lib/reporters/[object Object] from /Users/kitsonk/github/parser/node_modules/intern/lib/reporters/[object Object].js (parent: *15)
  at <node_modules/intern/node_modules/dojo/loader.ts:831:119>
  at <fs.js:208:20>
  at Object.oncomplete  <fs.js:108:15>
```

While the following works fine:

```js
reporters: [ 'Console', 'LcovHtml' ]
```

**Comment by jason0x43** [comment]
Is it the missing quote?

**Comment by sholladay** [comment]
Yeah, `LcovHtml` is missing a quote on the right.

**Comment by kitsonk** [comment]
@jason0x43 my typo in the issue, not in the observed behaviour, actually my configuration was technically:

```js
reporters: [
	{ id: 'Console' },
	{ id: 'LcovHtml', directory: 'html-report' },
	{ id: 'Lcov', filename: 'lcov.info' }
]
```

**Comment by kitsonk** [comment]
Also, to clarify, I am passing it in via a `Gruntfile.js`.

**Comment by csnover** [comment]
I am not able to reproduce any issue.

**Comment by sholladay** [comment]
Ah, I am able to reproduce this when putting the `reporters` property in `Gruntfile.js`, but it works as expected when used inside of the `intern.js` configuration file.

**Comment by sholladay** [comment]
From a quick glance, I think the bug is at [line 71](https://github.com/theintern/intern/blob/master/tasks/intern.js#L71) in tasks/intern.js

**Comment by csnover** [comment]
try with this:

```patch
diff --git a/tasks/intern.js b/tasks/intern.js
index 0014d25..bf1cfe1 100644
--- a/tasks/intern.js
+++ b/tasks/intern.js
@@ -43,6 +43,14 @@ module.exports = function (grunt) {
 		logOutput(data.slice(start));
 	}
 
+	function serialize(data) {
+		if (typeof data === 'object') {
+			return JSON.stringify(data);
+		}
+
+		return data;
+	}
+
 	grunt.registerMultiTask('intern', function () {
 		var done = this.async(),
 			opts = this.options({ runType: 'client' }),
@@ -68,7 +76,7 @@ module.exports = function (grunt) {
 
 			if (Array.isArray(value)) {
 				value.forEach(function (value) {
-					args.push(option + '=' + value);
+					args.push(option + '=' + serialize(value));
 				});
 			}
 			else if (typeof value === 'boolean') {
@@ -77,7 +85,7 @@ module.exports = function (grunt) {
 				}
 			}
 			else {
-				args.push(option + '=' + value);
+				args.push(option + '=' + serialize(value));
 			}
 		});
 
```

**Comment by sholladay** [comment]
That works for me. How about you, @kitsonk ?

**Comment by kitsonk** [comment]
Yes, works for me too.  :smiley: :+1:
