### ISSUE TITLE
Skipping loading unit tests is picky

### ISSUE THREAD

**Issue by sholladay** [theintern/intern#420]
From the [user guide](https://theintern.github.io/intern/#common-config):
> suites can also be set to null to skip loading the unit testing system when in runner mode.

For me, doing so leads to a fatal error on the client.

I would expect all falsey values (and frankly, an empty array) to behave the same in this manner. Currently, only `undefined` seems to work as expected.

````javascript
Fatal error during pre-execution stage

TypeError: mid is null
  at getModule  <__intern/node_modules/dojo/loader.js:247:9>
  at resolveDeps/<  <__intern/node_modules/dojo/loader.js:447:26>
  at resolveDeps  <__intern/node_modules/dojo/loader.js:446:1>
  at contextRequire  <__intern/node_modules/dojo/loader.js:141:23>
  at createRequire/result  <__intern/node_modules/dojo/loader.js:157:24>
  at Executor.prototype._loadTestModules/<  <__intern/lib/executors/Executor.js:231:1>
  at Promise  <__intern/node_modules/dojo/Promise.js:172:17>
  at Executor.prototype._loadTestModules  <__intern/lib/executors/Executor.js:230:1>
  at loadTestModules  <__intern/lib/executors/Client.js:59:12>
  at Promise/this.then/</<  <__intern/node_modules/dojo/Promise.js:156:41>
  at runCallbacks  <__intern/node_modules/dojo/Promise.js:19:13>
  at settle/<  <__intern/node_modules/dojo/Promise.js:103:21>
  at run  <__intern/node_modules/dojo/Promise.js:51:33>
  at CallbackQueue</CallbackQueue.prototype.drain  <__intern/node_modules/dojo/CallbackQueue.js:39:21>
  at nextTick</observer<  <__intern/node_modules/dojo/nextTick.js:52:21>
````

**Comment by sholladay** [comment]
This patch fixes it for me. Not sure if it appropriately handles all of the edge cases or assumptions from the rest of the system.

````diff
diff --git a/lib/executors/PreExecutor.js b/lib/executors/PreExecutor.js
index 8ea79c1..818a47f 100644
--- a/lib/executors/PreExecutor.js
+++ b/lib/executors/PreExecutor.js
@@ -213,9 +213,14 @@ define([
 				}
 
 				[ 'suites', 'functionalSuites', 'reporters' ].forEach(function (name) {
-					var value = config[name];
-					if (typeof value !== 'undefined' && !Array.isArray(value)) {
-						config[name] = value === '' ? [] : [ value ];
+					var value = config[name],
+					    isArray = Array.isArray(value);
+
+					if (value && !isArray) {
+						config[name] = [ value ];
+					}
+					else if (isArray && value.length < 1) {
+						config[name] = undefined;
 					}
 				});
 

````

**Comment by csnover** [comment]
@sholladay what about just this change:

```patch
diff --git a/lib/executors/PreExecutor.js b/lib/executors/PreExecutor.js
index 8ea79c1..2d05ccd 100644
--- a/lib/executors/PreExecutor.js
+++ b/lib/executors/PreExecutor.js
@@ -214,7 +216,7 @@ define([
 
                                [ 'suites', 'functionalSuites', 'reporters' ].forEach(function (name) {
                                        var value = config[name];
-                                       if (typeof value !== 'undefined' && !Array.isArray(value)) {
+                                       if (value != null && !Array.isArray(value)) {
                                                config[name] = value === '' ? [] : [ value ];
                                        }
                                });
```

**Comment by sholladay** [comment]
Good enough for me. :)

**Comment by csnover** [comment]
Well good because I already stuck it in there so it can’t ever be changed now!! :)
