### ISSUE TITLE
Regression in commit c3ead65e576aad4bc3 "Failed to load module dojo/node"

### ISSUE THREAD

**Issue by vladikoff** [theintern/intern#460]
## STR 

```
git clone https://github.com/vladikoff/intern-quick-test.git -b i450
cd intern-quick-test 
npm i
npm test
```

## Expected

```
npm test

> intern-quick-test@1.0.0 test /Users/vladikoff/tmp/intern-quick-test
> intern-runner config=intern.js

PASS: firefox on any platform - unit tests - suite1 - testTrue (10002ms)
0/1 tests failed
```

## Actual

```
 intern-quick-test git:(i450) npm test

> intern-quick-test@1.0.0 test /Users/vladikoff/tmp/intern-quick-test
> intern-runner config=intern.js

Error: Failed to load module dojo/node from /Users/vladikoff/tmp/intern-quick-test/dojo/node.js (parent: dojo/node!25!*)
  at <node_modules/intern/node_modules/dojo/loader.ts:831:119>
  at <fs.js:208:20>
  at Object.oncomplete  <fs.js:108:15>
npm ERR! Test failed.  See above for more details.
```

## Info

If you roll back one commit: 
```
npm i theintern/intern#ba89179be3147db7a191ab105c641f56ec5cabd2
npm test
``` 
then it will work

**Comment by csnover** [comment]
Good catch; when we try to load the tunnel we can’t use the global require as-is because accessing `dojo/node` relied on the loader map for `intern`.
