### ISSUE TITLE
When trying to contribute to the project "npm test" does not work

### ISSUE THREAD

**Issue by vladikoff** [theintern/intern#463]
Common pattern in node.js projects is for `npm test` to work and test the project locally before sending patches. This issues makes it harder to contribute to the project.

### STR

【 code  】
git clone git@github.com:theintern/intern.git
cd intern
npm i 
npm test
【 end code 】

### Actual

【 code  】
➜  intern git:(master) npm test

> intern@3.1.0-pre test /Users/vladikoff/dev/intern
> echo "Error: no test specified"

Error: no test specified
【 end code 】

### Expected

Project tests should run locally

SHA: 071cc6a7355e58923e3f36072eb5f52ce7db9712

**Comment by csnover** [comment]
You say expected “Project tests should run locally”. Which tests should run locally, and how? It should just invoke `tests/selftest.sh`?

**Comment by vladikoff** [comment]
Invoking `selftests.sh` causes: 
```
➜  intern git:(master) ./tests/selftest.sh 
Running client tests…
Running runner tests…
Starting tunnel
Download NaN% complete
Download 0.4279162347682839% complete
Download 0.5750820532074855% complete
Download 0.783183718344169% complete
Download 1.163745326964292% complete
Download 1.2677961595326335% complete
Download 1.6839994898060004% complete
Download 2.272662763562807% complete
Download 2.861326037319613% complete
Download 3.4499893110764193% complete
Download 4.038652584833226% complete
Download 4.627315858590032% complete
Download 5.215979132346839% complete
Download 5.804642406103644% complete
Download 6.393305679860452% complete
Download 6.9819689536172564% complete
Download 7.570632227374063% complete
Download 8.15929550113087% complete
Download 8.747958774887676% complete
Download 9.336622048644482% complete
Download 9.92528532240129% complete
Download 10.513948596158096% complete
Download 11.102611869914902% complete
Download 11.691275143671707% complete
Download 12.279938417428514% complete
Download 12.868601691185322% complete
Download 13.457264964942128% complete
Download 14.045928238698934% complete
Download 14.634591512455739% complete
Download 15.223254786212545% complete
Download 15.81191805996935% complete
Download 16.40058133372616% complete
Download 16.989244607482963% complete
Download 17.57790788123977% complete
Download 18.16657115499658% complete
Download 18.755234428753383% complete
Download 19.34389770251019% complete
Download 19.932560976267% complete
Download 20.521224250023803% complete
Download 21.10988752378061% complete
Download 21.698550797537415% complete
Download 22.287214071294223% complete
Download 22.87587734505103% complete
Download 23.464540618807835% complete
Download 24.053203892564643% complete
Download 24.641867166321447% complete
Download 25.23053044007825% complete
Download 25.81919371383506% complete
Download 26.407856987591867% complete
Download 26.99652026134867% complete
Download 27.58518353510548% complete
Download 28.173846808862287% complete
Download 28.76251008261909% complete
Download 29.3511733563759% complete
Download 29.939836630132703% complete
Download 30.52849990388951% complete
Download 31.11716317764632% complete
Download 31.705826451403123% complete
Download 32.29448972515993% complete
Download 32.883152998916735% complete
Download 33.47181627267354% complete
Download 34.06047954643035% complete
Download 34.64914282018716% complete
Download 35.237806093943966% complete
Download 35.82646936770077% complete
Download 36.415132641457575% complete
Download 37.00379591521438% complete
Download 37.59245918897119% complete
Download 38.181122462728% complete
Download 38.7697857364848% complete
Download 39.3584490102416% complete
Download 39.94711228399841% complete
Download 40.535775557755215% complete
Download 41.12443883151202% complete
Download 41.71310210526883% complete
Download 42.30176537902564% complete
Download 42.89042865278244% complete
Download 43.47909192653925% complete
Download 44.067755200296055% complete
Download 44.65641847405286% complete
Download 45.24508174780967% complete
Download 45.83374502156647% complete
Download 46.42240829532328% complete
Download 47.01107156908009% complete
Download 47.599734842836895% complete
Download 48.1883981165937% complete
Download 48.777061390350504% complete
Download 49.36572466410731% complete
Download 49.95438793786412% complete
Download 50.54305121162093% complete
Download 51.131714485377735% complete
Download 51.720377759134536% complete
Download 52.30904103289134% complete
Download 52.89770430664815% complete
Download 53.48636758040496% complete
Download 54.07503085416177% complete
Download 54.663694127918575% complete
Download 55.252357401675376% complete
Download 55.84102067543218% complete
Download 56.42968394918899% complete
Download 57.0183472229458% complete
Download 57.60701049670261% complete
Download 58.19567377045941% complete
Download 58.784337044216215% complete
Download 59.37300031797302% complete
Download 59.96166359172983% complete
Download 60.55032686548664% complete
Download 61.13899013924345% complete
Download 61.72765341300025% complete
Download 62.316316686757055% complete
Download 62.90497996051386% complete
Download 63.49364323427067% complete
Download 64.08230650802747% complete
Download 64.67096978178428% complete
Download 65.25963305554109% complete
Download 65.8482963292979% complete
Download 66.4369596030547% complete
Download 67.02562287681151% complete
Download 67.61428615056832% complete
Download 68.20294942432513% complete
Download 68.79161269808193% complete
Download 69.38027597183873% complete
Download 69.96893924559554% complete
Download 70.55760251935233% complete
Download 71.14626579310914% complete
Download 71.73492906686594% complete
Download 72.32359234062275% complete
Download 72.91225561437956% complete
Download 73.50091888813637% complete
Download 74.08958216189318% complete
Download 74.67824543564998% complete
Download 75.26690870940679% complete
Download 75.8555719831636% complete
Download 76.44423525692041% complete
Download 77.0328985306772% complete
Download 77.62156180443401% complete
Download 78.21022507819082% complete
Download 78.79888835194762% complete
Download 79.38755162570443% complete
Download 79.97621489946124% complete
Download 80.56487817321805% complete
Download 81.15354144697486% complete
Download 81.74220472073166% complete
Download 82.33086799448847% complete
Download 82.91953126824527% complete
Download 83.50819454200207% complete
Download 84.09685781575888% complete
Download 84.68552108951569% complete
Download 85.2741843632725% complete
Download 85.8628476370293% complete
Download 86.45151091078611% complete
Download 87.04017418454292% complete
Download 87.62883745829973% complete
Download 88.21750073205654% complete
Download 88.80616400581334% complete
Download 89.39482727957014% complete
Download 89.98349055332694% complete
Download 90.57215382708375% complete
Download 91.16081710084056% complete
Download 91.74948037459737% complete
Download 92.33814364835418% complete
Download 92.92680692211098% complete
Download 93.51547019586779% complete
Download 94.1041334696246% complete
Download 94.69279674338141% complete
Download 95.28146001713822% complete
Download 95.87012329089501% complete
Download 96.45878656465182% complete
Download 97.04744983840862% complete
Download 97.63611311216543% complete
Download 98.22477638592224% complete
Download 98.81343965967905% complete
Download 99.40210293343586% complete
Download 99.99076620719266% complete
Download 100% complete
Tunnel: BrowserStackLocal v3.7
Tunnel: Error: The tunnel reported: You provided an invalid key
Error: The tunnel reported: You provided an invalid key
  at Socket.<anonymous>  <node_modules/intern/node_modules/digdug/BrowserStackTunnel.js:201:16>
  at Socket.emit  <events.js:117:20>
  at Socket.<anonymous>  <_stream_readable.js:765:14>
  at Socket.emit  <events.js:92:17>
  at emitReadable_  <_stream_readable.js:427:10>
  at emitReadable  <_stream_readable.js:423:5>
  at readableAddChunk  <_stream_readable.js:166:9>
  at Socket.Readable.push  <_stream_readable.js:128:10>
  at Pipe.onread  <net.js:529:21>
```

Seems like that would require a browserstack key.
A few options come to mind:
- set the key as part of `npm test`

or

- run tests locally (no browserstack) with local browsers (chrome, firefox, or both) via `npm test`.
let the CI do browserstack work

or 

- provide `npm test` for local only testing, provide `npm run test-remote` to test with browserstack

**Comment by vladikoff** [comment]
With increased number of contributions I think it is crucial to fix this. (Also fix the CI Tests because they are always red)

**Comment by jason0x43** [comment]
`npm test` now works for running node-based unit tests. Run `npm test config=@wd` to run webdriver tests locally in Chrome.
