### ISSUE TITLE
Code coverage issue on Android ≤4.4

### ISSUE THREAD

**Issue by tomsterritt** [theintern/intern#472]
Running javascript functional tests on SauceLabs I get the following error on Android 4.1/4.3/4.4 browser:

```
SyntaxError: Unexpected token o
  at Object.parse  <native>
  at <node_modules/intern/lib/ProxiedSession.js:84:67>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at runCallbacks  <node_modules/intern/node_modules/dojo/Promise.ts:11:11>
  at <node_modules/intern/node_modules/dojo/Promise.ts:317:4>
  at run  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at <node_modules/intern/node_modules/dojo/nextTick.ts:44:3>
  at process._tickCallback  <node.js:355:11>
  at Command.target.(anonymous function) [as get]  <node_modules/intern/node_modules/leadfoot/Command.js:610:11>
  at Test.registerSuite.{mytestname} [as test]  </{mytestfile}.js:12:17>
  at <node_modules/intern/lib/Test.js:211:24>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at runCallbacks  <node_modules/intern/node_modules/dojo/Promise.ts:11:11>
  at <node_modules/intern/node_modules/dojo/Promise.ts:317:4>
  at run  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at <node_modules/intern/node_modules/dojo/nextTick.ts:44:3>
  at process._tickCallback  <node.js:355:11>
```

(Sorry if this should've been a question on SO, not entirely sure if bug or my fault)

**Comment by csnover** [comment]
If the server is creating garbage JSON, I doubt there is anything that we can do. We warn about using Sauce Labs in the user guide for a reason, it’s not some kind of vendetta. :) What is your configuration?

**Comment by csnover** [comment]
Since I haven’t heard any more information in two weeks I’m closing this ticket, but if you could respond back with information if this is still a problem I will be happy to reopen it then.
