### ISSUE TITLE
Intern 3.0.4 broke Android tests (at least on SauceLabs)

### ISSUE THREAD

**Issue by wkeese** [theintern/intern#505]
This is a regression from Intern 3.0.3 --> 3.0.4.   Using Intern 3.0.4 I get this error on startup when running against Android:

```
SyntaxError: Unexpected token a
  at Object.parse  <native>
  at <node_modules/intern/lib/ProxiedSession.js:84:67>
  at <node_modules/leadfoot/node_modules/dojo/Promise.ts:393:15>
  at runCallbacks  <node_modules/leadfoot/node_modules/dojo/Promise.ts:11:11>
  at <node_modules/leadfoot/node_modules/dojo/Promise.ts:317:4>
  at run  <node_modules/leadfoot/node_modules/dojo/Promise.ts:237:7>
  at <node_modules/leadfoot/node_modules/dojo/nextTick.ts:44:3>
  at doNTCallback0  <node.js:407:9>
  at process._tickCallback  <node.js:336:13>
  at Command.target.(anonymous function) [as get]  <node_modules/leadfoot/Command.js:610:11>
  at ClientSuite.lang.mixin.run  <node_modules/intern/lib/ClientSuite.js:149:6>
  at runWithCatch  <node_modules/intern/lib/Suite.js:314:21>
  at next  <node_modules/intern/lib/Suite.js:322:18>
  at <node_modules/intern/lib/Suite.js:345:6>
  at new Promise  <node_modules/intern/node_modules/dojo/Promise.ts:411:3>
  at runTests  <node_modules/intern/lib/Suite.js:278:12>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at runCallbacks  <node_modules/intern/node_modules/dojo/Promise.ts:11:11>
  at <node_modules/intern/node_modules/dojo/Promise.ts:317:4>
```

It worked with Intern 3.0.3.

The environment setting is:

```js
environments: [
	{ browserName: "android", platform: "Linux", version: "5.1", deviceName: "Android Emulator" }
],
```

Looking at the Selenium log, it's possibly failing on these commands:

```
POST execute script: "return document.getElementById(\"a\");" => {"ELEMENT":":wdc:1443404422140"}
GET element/%3Awdc%3A1443404422140/size
```

**Comment by csnover** [comment]
Can you please tell me what is the value of `coverageData` in the top-most frame when this crash occurs?

**Comment by wkeese** [comment]
It's "about:blank".

**Comment by wkeese** [comment]
Looks like the problem started with theintern/leadfoot@cecdc2f816bd5aa1a72df2678208d5662c14ae55.

**Comment by wkeese** [comment]
Thanks, I didn't try 3.0.5 but 3.0.6 seems to be working.
