### ISSUE TITLE
Failed unit test, not even properly connected, marked as success in TestingBot interface.

### ISSUE THREAD

**Issue by ghost** [theintern/intern#507]
See https://testingbot.com/tests/6131223.

End of terminal output (intern run via grunt):

```
SUITE ERROR
Error: [POST http://(redacted)@localhost:4445/wd/hub/session/d58d9cc7-402a-452d-8240-afcfc156d8c2/url / {"url":"http:
//localhost:9000/__intern/client.html?build=if87w8ko&tunnel=TestingBotTunnel&config=tests%2Funit&environments=%5Bobje
ct%20Object%5D&environments=%5Bobject%20Object%5D&environments=%5Bobject%20Object%5D&environments=%5Bobject%20Object%
5D&reporters=%7B%22id%22%3A%22WebDriver%22%7D&basePath=%2F&initialBaseUrl=%2F&rootSuiteName=microsoftedge%20on%20any%
20platform%20-%20unit%20tests&sessionId=d58d9cc7-402a-452d-8240-afcfc156d8c2"}]
at runRequest  <node_modules\intern\node_modules\leadfoot\Session.js:88:40>
at <node_modules\intern\node_modules\leadfoot\Session.js:109:39>
at new Promise  <node_modules\intern\node_modules\dojo\Promise.ts:411:3>
at ProxiedSession._post  <node_modules\intern\node_modules\leadfoot\Session.js:63:10>
at ProxiedSession.Session.get  <node_modules\intern\node_modules\leadfoot\Session.js:575:15>
at <node_modules\intern\lib\ProxiedSession.js:86:25>
at getFinalValue  <node_modules\intern\node_modules\dojo\Promise.ts:462:21>
at <node_modules\intern\node_modules\dojo\Promise.ts:482:10>
at <node_modules\intern\node_modules\dojo\Promise.ts:393:15>
at runCallbacks  <node_modules\intern\node_modules\dojo\Promise.ts:11:11>
at Command.target.(anonymous function) [as get]  <node_modules\intern\node_modules\leadfoot\Command.js:610:11>
at ClientSuite.lang.mixin.run  <node_modules\intern\lib\ClientSuite.js:149:6>
at runWithCatch  <node_modules\intern\lib\Suite.js:314:21>
at next  <node_modules\intern\lib\Suite.js:322:18>
at <node_modules\intern\lib\Suite.js:345:6>
at new Promise  <node_modules\intern\node_modules\dojo\Promise.ts:411:3>
at runTests  <node_modules\intern\lib\Suite.js:278:12>
at <node_modules\intern\node_modules\dojo\Promise.ts:393:15>
at runCallbacks  <node_modules\intern\node_modules\dojo\Promise.ts:11:11>
at <node_modules\intern\node_modules\dojo\Promise.ts:317:4>
>> 0/0 tests failed
Error: One or more suite errors occurred during testing
at <node_modules\intern\lib\executors\Executor.js:301:13>
at <node_modules\intern\node_modules\dojo\Promise.ts:393:15>
at runCallbacks  <node_modules\intern\node_modules\dojo\Promise.ts:11:11>
at <node_modules\intern\node_modules\dojo\Promise.ts:317:4>
at run  <node_modules\intern\node_modules\dojo\Promise.ts:237:7>
at <node_modules\intern\node_modules\dojo\nextTick.ts:44:3>
at doNTCallback0  <node.js:407:9>
at process._tickCallback  <node.js:336:13>
Warning: Test failure; check output above for details. Use --force to continue.

Aborted due to warnings.

```

**Comment by csnover** [comment]
I am assuming based on the information you’ve provided that the issue here is that the run was not marked as failure *in the TestingBot interface*, not that it didn’t fail on the machine where it was running.

**Comment by csnover** [comment]
I am assuming based on the information you’ve provided that the issue here is that the run was not marked as failure *in the TestingBot interface*, not that it didn’t fail on the machine where it was running. Is that correct?

**Comment by herby** [comment]
Yes, sorry for not specifying it properly. It was about incorrectly reporting "success" back to TestingBot.

**Comment by jason0x43** [comment]
Closing this due to inactivity
