### ISSUE TITLE
Edge12 / IE12 not running via BrowserStack

### ISSUE THREAD

**Issue by rodneyrehm** [theintern/intern#555]
Hey there!

I was giving it another shot to run my tests on Edge via BrowserStack. Intern is not getting past its initial environment checks. here's the [raw log](https://gist.github.com/rodneyrehm/a566fb5d1d238ba1210f) and here the part of the "Text Log" showing where it's failing:

<img width="1045" alt="screen shot 2015-12-13 at 11 41 48" src="https://cloud.githubusercontent.com/assets/186837/11766587/fea2295a-a18e-11e5-82ce-5120cad58ffc.png">

This is what the console had to say:

```
Suite Edge12 on WIN - unit tests FAILED
UnknownError: [POST http://(redacted)@hub.browserstack.com:4444/wd/hub/session/<session-id>/url / {"url":"http://localhost:9000/__intern/client.html?config=test%2Fbrowserstack&basePath=%2F&initialBaseUrl=%2F&reporters=%7B%22id%22%3A%22WebDriver%22%7D&rootSuiteName=Edge12%20on%20WIN%20-%20unit%20tests&sessionId=<session-id>"}] Session not started or terminated
  at runRequest  <node_modules/intern/node_modules/leadfoot/Session.js:88:40>
  at <node_modules/intern/node_modules/leadfoot/Session.js:109:39>
  at new Promise  <node_modules/intern/node_modules/dojo/Promise.ts:411:3>
  at ProxiedSession._post  <node_modules/intern/node_modules/leadfoot/Session.js:63:10>
  at ProxiedSession.Session.get  <node_modules/intern/node_modules/leadfoot/Session.js:575:15>
  at <node_modules/intern/lib/ProxiedSession.js:86:25>
  at getFinalValue  <node_modules/intern/node_modules/dojo/Promise.ts:462:21>
  at <node_modules/intern/node_modules/dojo/Promise.ts:482:10>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at runCallbacks  <node_modules/intern/node_modules/dojo/Promise.ts:11:11>
  at Command.target.(anonymous function) [as get]  <node_modules/intern/node_modules/leadfoot/Command.js:610:11>
  at ClientSuite.lang.mixin.run  <node_modules/intern/lib/ClientSuite.js:149:6>
  at runWithCatch  <node_modules/intern/lib/Suite.js:314:21>
  at next  <node_modules/intern/lib/Suite.js:322:18>
  at <node_modules/intern/lib/Suite.js:345:6>
  at new Promise  <node_modules/intern/node_modules/dojo/Promise.ts:411:3>
  at runTests  <node_modules/intern/lib/Suite.js:278:12>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at runCallbacks  <node_modules/intern/node_modules/dojo/Promise.ts:11:11>
  at <node_modules/intern/node_modules/dojo/Promise.ts:317:4>
No unit test coverage for Edge12 on WIN
```

At the moment I'm running Intern in the version [`rodneyrehm/intern#fix/proxy-mimetypes`](https://github.com/rodneyrehm/intern/tree/fix/proxy-mimetypes) (because no beta containing this fix has been released yet).

Am I missing any particular capability (I haven't set anything but the defaults)? How can I help to debug this?

**Comment by csnover** [comment]
The best thing would be to [run the Leadfoot test suite](https://github.com/theintern/leadfoot/blob/master/tests/run.sh) against Edge. That will run every command and tell you exactly which ones don’t work. Basically you will be fixing https://github.com/theintern/leadfoot/issues/67.

**Comment by rodneyrehm** [comment]
thx for the pointer! I'll try to have a look at it soon :)

**Comment by rodneyrehm** [comment]
Are the leadfoot tests supposed to pass? I see several failures (without having touched anything):

```
FAIL: internet explorer 10 on WIN8 - leadfoot/helpers/pollUntil - early timeout
FAIL: internet explorer 10 on WIN8 - Server - error handling
FAIL: internet explorer 10 on WIN8 - Server - error output security
FAIL: internet explorer 10 on WIN8 - Server - #getSessions

FAIL: internet explorer 11 on WIN8 - Server - error handling
FAIL: internet explorer 11 on WIN8 - Server - error output security
FAIL: internet explorer 11 on WIN8 - Server - #getSessions

FAIL: internet explorer 9 on WINDOWS - leadfoot/helpers/pollUntil - early timeout
FAIL: internet explorer 9 on WINDOWS - Server - error handling
FAIL: internet explorer 9 on WINDOWS - Server - error output security
FAIL: internet explorer 9 on WINDOWS - Server - #getSessions
FAIL: internet explorer 9 on WINDOWS - Session - frame switching (#switchToFrame, #switchToParentFrame)
FAIL: internet explorer 9 on WINDOWS - Element - #type -> file upload

FAIL: firefox 33 on WINDOWS - Server - error handling
FAIL: firefox 33 on WINDOWS - Server - error output security
FAIL: firefox 33 on WINDOWS - Server - #getSessions
FAIL: firefox 33 on WINDOWS - Command - #moveMouseTo usesElement

FAIL: firefox 33 on MAC - Server - error handling
FAIL: firefox 33 on MAC - Server - error output security
FAIL: firefox 33 on MAC - Server - #getSessions

FAIL: chrome 38 on WINDOWS - Server - error handling
FAIL: chrome 38 on WINDOWS - Server - error output security
FAIL: chrome 38 on WINDOWS - Server - #getSessions
FAIL: chrome 38 on WINDOWS - Session - geolocation (#getGeolocation, #setGeolocation)

FAIL: chrome 38 on MAC - Server - error handling
FAIL: chrome 38 on MAC - Server - error output security
FAIL: chrome 38 on MAC - Server - #getSessions
FAIL: chrome 38 on MAC - Session - window sizing (#getWindowSize, #setWindowSize)
FAIL: chrome 38 on MAC - Session - geolocation (#getGeolocation, #setGeolocation)

FAIL: safari 8 on MAC - Server - error handling
FAIL: safari 8 on MAC - Server - error output security
FAIL: safari 8 on MAC - Server - #getSessions
FAIL: safari 8 on MAC - Session - frame switching (#switchToFrame, #switchToParentFrame)
FAIL: safari 8 on MAC - Element - #type -> file upload
```

In a second run I've added Microsoft Edge to the environment, for which I'm getting the following errors:

```
FAIL: Edge12 on WIN - leadfoot/helpers/pollUntil - basic test
FAIL: Edge12 on WIN - leadfoot/helpers/pollUntil - without args
FAIL: Edge12 on WIN - leadfoot/helpers/pollUntil - early timeout
FAIL: Edge12 on WIN - leadfoot/helpers/pollUntil - iteration check

FAIL: Edge12 on WIN - Server - error handling
FAIL: Edge12 on WIN - Server - error output security
FAIL: Edge12 on WIN - Server - #getSessions
FAIL: Edge12 on WIN - Server - #getSessionCapabilities

a whole lot of
UnknownError: [POST http://(redacted)@hub.browserstack.com:4444/wd/hub/session/<session-id>/url / {"url":"about:blank"}] Session not started or terminated

FAIL: Edge12 on WIN - leadfoot/compat - #waitForElement
FAIL: Edge12 on WIN - leadfoot/compat - #waitForElement context
FAIL: Edge12 on WIN - leadfoot/compat - #waitForVisible
FAIL: Edge12 on WIN - leadfoot/compat - #text
```

The VM instance on BrowserStack presents the same as in the original report. I'm not sure I've acquired any new insights…

**Comment by csnover** [comment]
The test suite doesn’t work well against cloud providers because they break additional things and I haven’t ever managed to get them to not do that. (The error handling and getSessions failures are because BrowserStack doesn’t respond to those calls correctly, even though Selenium itself does.) It’s possible that some of those test failures are legitimate but you’ll need to test against a local VM to know for sure. As far as “new insights”, I’m not sure what to tell you. To fix the problem, you’ll need to troubleshoot the failing tests to learn why they are failing.

**Comment by rodneyrehm** [comment]
> The error handling and getSessions failures are because BrowserStack doesn’t respond to those calls correctly, even though Selenium itself does.

If incorrect response means "correct data, wrong format", the ingestion of the response could handle that, right? Is that something you've considered? Or am I on the wrong track an it's technically not possible/worthwhile?

> […]  but you’ll need to test against a local VM to know for sure

Any pointers on how to make that happen easily? Can I just fire up [selenium-standalone](https://www.npmjs.com/package/selenium-standalone) in the VM, make the tests use NullTunnel and that's it? Happy to do the legwork, once I've figured out how to actually run the tests…

**Comment by csnover** [comment]
> If incorrect response means "correct data, wrong format", the ingestion of the response could handle that, right? Is that something you've considered? Or am I on the wrong track an it's technically not possible/worthwhile?

It maybe possible to deal with the bad `getSessions` response—I don’t know exactly what is wrong with the response. The error handling is a bigger problem, IIRC, because the test basically sends a request to an endpoint that should definitely be responding with a 4xx error, and instead BS responds with success. In a sense, that test doesn’t need to exist at all, but in another, it means that it may be impossible to feature detect on that service.

> Any pointers on how to make that happen easily?

I haven’t looked into what you have to do to get an Edge WebDriver server running. If it is like ChromeDriver then all you need to do is run the Edge WD server. Otherwise you would need to get Selenium & the Edge WD and run it according to their instructions. Then as you described you would use the NullTunnel and set the tunnelOptions host/port/path to match the local service. If you are using an actual VM and running Intern outside of the VM you will also need to set proxyUrl correctly (IIRC in VirtualBox it’s 10.0.2.2 to access the host machine so your proxyUrl would be `http://10.0.2.2:9000`). Hope that helps!

**Comment by jason0x43** [comment]
Is this still a problem? I've run Intern's self tests against Edge on Browserstack recently and they didn't have any issues.

**Comment by rodneyrehm** [comment]
The last time I tried this was with Edge 12. Currently you get Edge13 on BrowserStack. I just updated to Intern's master (9092e46) and tried running the [ally.js suite](https://github.com/medialize/ally.js/blob/master/test/intern.js) on BrowserStack's Edge13 and got the following errors in the CLI (and the [raw browserstack log](https://gist.github.com/rodneyrehm/57c2842206ae825c14bb)):

```
Suite Edge13 on WIN - unit tests FAILED
UnknownError: [POST http://(redacted)@hub.browserstack.com:4444/wd/hub/session/<session>/url / {"url":"http://localhost:9000/__intern/client.html?config=test%2Fbrowserstack&basePath=%2F&initialBaseUrl=%2F&reporters=%7B%22id%22%3A%22WebDriver%22%7D&rootSuiteName=Edge13%20on%20WIN%20-%20unit%20tests&sessionId=<session>"}] Unable to communicate to node
  at runRequest  <node_modules/intern/node_modules/leadfoot/Session.js:88:40>
  at <node_modules/intern/node_modules/leadfoot/Session.js:109:39>
  at new Promise  <node_modules/intern/node_modules/dojo/Promise.ts:411:3>
  at ProxiedSession._post  <node_modules/intern/node_modules/leadfoot/Session.js:63:10>
  at ProxiedSession.Session.get  <node_modules/intern/node_modules/leadfoot/Session.js:575:15>
  at <node_modules/intern/lib/ProxiedSession.js:86:25>
  at getFinalValue  <node_modules/intern/node_modules/dojo/Promise.ts:462:21>
  at <node_modules/intern/node_modules/dojo/Promise.ts:478:10>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at runCallbacks  <node_modules/intern/node_modules/dojo/Promise.ts:11:11>
  at Command.target.(anonymous function) [as get]  <node_modules/intern/node_modules/leadfoot/Command.js:610:11>
  at ClientSuite.lang.mixin.run  <node_modules/intern/lib/ClientSuite.js:149:6>
  at runWithCatch  <node_modules/intern/lib/Suite.js:314:21>
  at next  <node_modules/intern/lib/Suite.js:322:18>
  at <node_modules/intern/lib/Suite.js:345:6>
  at new Promise  <node_modules/intern/node_modules/dojo/Promise.ts:411:3>
  at runTests  <node_modules/intern/lib/Suite.js:278:12>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at runCallbacks  <node_modules/intern/node_modules/dojo/Promise.ts:11:11>
  at <node_modules/intern/node_modules/dojo/Promise.ts:317:4>
Suite Edge13 on WIN - intern/events FAILED
UnknownError: [POST http://(redacted)@hub.browserstack.com:4444/wd/hub/session/<session>/url / {"url":"http://localhost:9000/test/pages/intern.events.test.html"}] Session not started or terminated
  at runRequest  <node_modules/intern/node_modules/leadfoot/Session.js:88:40>
  at <node_modules/intern/node_modules/leadfoot/Session.js:109:39>
  at new Promise  <node_modules/intern/node_modules/dojo/Promise.ts:411:3>
  at ProxiedSession._post  <node_modules/intern/node_modules/leadfoot/Session.js:63:10>
  at ProxiedSession.Session.get  <node_modules/intern/node_modules/leadfoot/Session.js:575:15>
  at <node_modules/intern/lib/ProxiedSession.js:86:25>
  at getFinalValue  <node_modules/intern/node_modules/dojo/Promise.ts:462:21>
  at <node_modules/intern/node_modules/dojo/Promise.ts:482:10>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at runCallbacks  <node_modules/intern/node_modules/dojo/Promise.ts:11:11>
  at Command.target.(anonymous function) [as get]  <node_modules/intern/node_modules/leadfoot/Command.js:610:11>
  at Suite.before  <test/functional/intern.events.test.js:146:12>
  at Suite.target.(anonymous function).dispatcher [as setup]  <node_modules/intern/node_modules/dojo/aspect.ts:102:35>
  at <node_modules/intern/lib/Suite.js:351:33>
  at new Promise  <node_modules/intern/node_modules/dojo/Promise.ts:411:3>
  at setup  <node_modules/intern/lib/Suite.js:350:12>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at runCallbacks  <node_modules/intern/node_modules/dojo/Promise.ts:11:11>
  at <node_modules/intern/node_modules/dojo/Promise.ts:317:4>
  at run  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
Suite Edge13 on WIN - maintain/tab-focus FAILED
TypeError: callback.call is not a function
  at runCallback  <node_modules/intern/node_modules/leadfoot/Command.js:526:31>
  at Command.<anonymous>  <node_modules/intern/node_modules/leadfoot/Command.js:545:11>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at run  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at <node_modules/intern/node_modules/dojo/nextTick.ts:44:3>
  at doNTCallback0  <node.js:419:9>
  at process._tickCallback  <node.js:348:13>
  at Command.then  <node_modules/intern/node_modules/leadfoot/Command.js:542:10>
  at Suite.before  <test/functional/maintain.tab-focus.test.js:45:12>
  at Suite.target.(anonymous function).dispatcher [as setup]  <node_modules/intern/node_modules/dojo/aspect.ts:102:35>
  at <node_modules/intern/lib/Suite.js:351:33>
  at new Promise  <node_modules/intern/node_modules/dojo/Promise.ts:411:3>
  at setup  <node_modules/intern/lib/Suite.js:350:12>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at runCallbacks  <node_modules/intern/node_modules/dojo/Promise.ts:11:11>
  at <node_modules/intern/node_modules/dojo/Promise.ts:317:4>
  at run  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
Suite Edge13 on WIN - fix/pointer-focus-children FAILED
UnknownError: [POST http://(redacted)@hub.browserstack.com:4444/wd/hub/session/<session>/url / {"url":"http://localhost:9000/test/pages/fix.pointer-focus-children.test.html"}] Session not started or terminated
  at runRequest  <node_modules/intern/node_modules/leadfoot/Session.js:88:40>
  at <node_modules/intern/node_modules/leadfoot/Session.js:109:39>
  at new Promise  <node_modules/intern/node_modules/dojo/Promise.ts:411:3>
  at ProxiedSession._post  <node_modules/intern/node_modules/leadfoot/Session.js:63:10>
  at ProxiedSession.Session.get  <node_modules/intern/node_modules/leadfoot/Session.js:575:15>
  at <node_modules/intern/lib/ProxiedSession.js:86:25>
  at getFinalValue  <node_modules/intern/node_modules/dojo/Promise.ts:462:21>
  at <node_modules/intern/node_modules/dojo/Promise.ts:482:10>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at runCallbacks  <node_modules/intern/node_modules/dojo/Promise.ts:11:11>
  at Command.target.(anonymous function) [as get]  <node_modules/intern/node_modules/leadfoot/Command.js:610:11>
  at Suite.before  <test/functional/fix.pointer-focus-children.test.js:58:12>
  at Suite.target.(anonymous function).dispatcher [as setup]  <node_modules/intern/node_modules/dojo/aspect.ts:102:35>
  at <node_modules/intern/lib/Suite.js:351:33>
  at new Promise  <node_modules/intern/node_modules/dojo/Promise.ts:411:3>
  at setup  <node_modules/intern/lib/Suite.js:350:12>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at runCallbacks  <node_modules/intern/node_modules/dojo/Promise.ts:11:11>
  at <node_modules/intern/node_modules/dojo/Promise.ts:317:4>
  at run  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
Suite Edge13 on WIN - fix/pointer-focus-input FAILED
UnknownError: [POST http://(redacted)@hub.browserstack.com:4444/wd/hub/session/<session>/url / {"url":"http://localhost:9000/test/pages/fix.pointer-focus-input.test.html"}] Session not started or terminated
  at runRequest  <node_modules/intern/node_modules/leadfoot/Session.js:88:40>
  at <node_modules/intern/node_modules/leadfoot/Session.js:109:39>
  at new Promise  <node_modules/intern/node_modules/dojo/Promise.ts:411:3>
  at ProxiedSession._post  <node_modules/intern/node_modules/leadfoot/Session.js:63:10>
  at ProxiedSession.Session.get  <node_modules/intern/node_modules/leadfoot/Session.js:575:15>
  at <node_modules/intern/lib/ProxiedSession.js:86:25>
  at getFinalValue  <node_modules/intern/node_modules/dojo/Promise.ts:462:21>
  at <node_modules/intern/node_modules/dojo/Promise.ts:482:10>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at runCallbacks  <node_modules/intern/node_modules/dojo/Promise.ts:11:11>
  at Command.target.(anonymous function) [as get]  <node_modules/intern/node_modules/leadfoot/Command.js:610:11>
  at Suite.before  <test/functional/fix.pointer-focus-input.test.js:62:12>
  at Suite.target.(anonymous function).dispatcher [as setup]  <node_modules/intern/node_modules/dojo/aspect.ts:102:35>
  at <node_modules/intern/lib/Suite.js:351:33>
  at new Promise  <node_modules/intern/node_modules/dojo/Promise.ts:411:3>
  at setup  <node_modules/intern/lib/Suite.js:350:12>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at runCallbacks  <node_modules/intern/node_modules/dojo/Promise.ts:11:11>
  at <node_modules/intern/node_modules/dojo/Promise.ts:317:4>
  at run  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
Suite Edge13 on WIN - fix/pointer-focus-parent FAILED
UnknownError: [POST http://(redacted)@hub.browserstack.com:4444/wd/hub/session/<session>/url / {"url":"http://localhost:9000/test/pages/fix.pointer-focus-parent.test.html"}] Session not started or terminated
  at runRequest  <node_modules/intern/node_modules/leadfoot/Session.js:88:40>
  at <node_modules/intern/node_modules/leadfoot/Session.js:109:39>
  at new Promise  <node_modules/intern/node_modules/dojo/Promise.ts:411:3>
  at ProxiedSession._post  <node_modules/intern/node_modules/leadfoot/Session.js:63:10>
  at ProxiedSession.Session.get  <node_modules/intern/node_modules/leadfoot/Session.js:575:15>
  at <node_modules/intern/lib/ProxiedSession.js:86:25>
  at getFinalValue  <node_modules/intern/node_modules/dojo/Promise.ts:462:21>
  at <node_modules/intern/node_modules/dojo/Promise.ts:482:10>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at runCallbacks  <node_modules/intern/node_modules/dojo/Promise.ts:11:11>
  at Command.target.(anonymous function) [as get]  <node_modules/intern/node_modules/leadfoot/Command.js:610:11>
  at Suite.before  <test/functional/fix.pointer-focus-parent.test.js:71:12>
  at Suite.target.(anonymous function).dispatcher [as setup]  <node_modules/intern/node_modules/dojo/aspect.ts:102:35>
  at <node_modules/intern/lib/Suite.js:351:33>
  at new Promise  <node_modules/intern/node_modules/dojo/Promise.ts:411:3>
  at setup  <node_modules/intern/lib/Suite.js:350:12>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at runCallbacks  <node_modules/intern/node_modules/dojo/Promise.ts:11:11>
  at <node_modules/intern/node_modules/dojo/Promise.ts:317:4>
  at run  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
Suite Edge13 on WIN - observe/interaction-type FAILED
TypeError: callback.call is not a function
  at runCallback  <node_modules/intern/node_modules/leadfoot/Command.js:526:31>
  at Command.<anonymous>  <node_modules/intern/node_modules/leadfoot/Command.js:545:11>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at run  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at <node_modules/intern/node_modules/dojo/nextTick.ts:44:3>
  at doNTCallback0  <node.js:419:9>
  at process._tickCallback  <node.js:348:13>
  at Command.then  <node_modules/intern/node_modules/leadfoot/Command.js:542:10>
  at Suite.before  <test/functional/observe.interaction-type.test.js:24:12>
  at Suite.target.(anonymous function).dispatcher [as setup]  <node_modules/intern/node_modules/dojo/aspect.ts:102:35>
  at <node_modules/intern/lib/Suite.js:351:33>
  at new Promise  <node_modules/intern/node_modules/dojo/Promise.ts:411:3>
  at setup  <node_modules/intern/lib/Suite.js:350:12>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at runCallbacks  <node_modules/intern/node_modules/dojo/Promise.ts:11:11>
  at <node_modules/intern/node_modules/dojo/Promise.ts:317:4>
  at run  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
```

**Comment by LingSpb** [comment]
@rodneyrehm The error you got ("Unable to communicate to node"), I guess on March 2nd, was BrowserStack error. I got the same error that day, and later they confirmed that it was their fault and they have fixed it. Maybe you can try to run your tests again?

**Comment by rodneyrehm** [comment]
@LingSpb I can confirm the tests are now executed in Edge 13 on BrowserStack. Thanks for the ping!
