### ISSUE TITLE
When Intern timeouts on exit, throws a TypeError

### ISSUE THREAD

**Issue by kitsonk** [theintern/intern#576]
When a NodeJS environment does not try to shutdown on a timely basis after Intern has finished executing, Intern logs that it thinks NodeJS has hung and then exits, but does not [provide an exit code](https://github.com/theintern/intern/blob/76bb4109e5715371b5699edd823f6e7e3197f754/lib/exitHandler.js#L37) and then throws a type error:

```sh
Node.js hang detected; make sure to close all sockets, timers, and servers you opened during testing!
TypeError: Insufficient number of arguments.
at TypeError  <native>
at null._onTimeout  <node_modules/intern/lib/exitHandler.js:37:13>
at Timer.unrefdHandle  <timers.js:312:14>
```

**Comment by csnover** [comment]
The exit codes are normally provided by the `process.once('exit')` event listeners. This is some new API change/regression in Node.js if it can’t handle the zero-argument call to `process.exit`. What Node.js version does this start happening on?

**Comment by jason0x43** [comment]
It doesn't seem to be due to an intentional change in Node. At least, the current docs still list the exit code as optional, a number of Node's self tests call `process.exit()`, and simply doing what the exit handler does (calling `process.exit()` in an unrefed timer) doesn't produce that error, at least not in any of my trials.  (I tested with Node 0.10.35 ,0.11.0, 0.12.0, and 5.5.0.)

**Comment by sholladay** [comment]
There have been some problems with unref'd timers recently, I wonder if they could be provoking this somehow.

https://github.com/nodejs/node/issues/1264

Even though that ticket was.closed in late 2015, they are still calling it out in the release notes under Known Issues.

**Comment by jason0x43** [comment]
Is this still a recurring issue, or has it been overcome by events? I was getting a NodeJS hang message consistently when using one of the Dig Dug tunnels (it wasn't shutting down properly), but never saw a TypeError.

**Comment by jason0x43** [comment]
Closing this due to inactivity
