### ISSUE TITLE
Quality of error output of reporter "Runner"

### ISSUE THREAD

**Issue by rodneyrehm** [theintern/intern#583]
Hey there,

when running tests via `intern-runner` I get the following output:

```
× <browser> - unit tests - <suite> - <test> (0.113s)
AssertionError: expected [ 'alpha', 'bravo' ] to deeply equal [ Array(4) ]
  at AssertionError  <__intern/node_modules/chai/chai.js:4760:18>
  at [2]</module.exports/Assertion.prototype.assert  <__intern/node_modules/chai/chai.js:203:1>
  at assertEql  <__intern/node_modules/chai/chai.js:765:1>
  at [9]</module.exports/ctx[name]  <__intern/node_modules/chai/chai.js:3475:18>
  at assertEqual  <__intern/node_modules/chai/chai.js:731:14>
  at [9]</module.exports/ctx[name]  <__intern/node_modules/chai/chai.js:3475:18>
  at suite["<test>"]  <test/unit/test-file.js:192:7>
  at Test.prototype.run/<  <__intern/lib/Test.js:211:19>
  at Promise/this.then/</<  <__intern/node_modules/dojo/Promise.js:156:41>
  at runCallbacks  <__intern/node_modules/dojo/Promise.js:19:13>
  at settle/<  <__intern/node_modules/dojo/Promise.js:103:21>
  at run  <__intern/node_modules/dojo/Promise.js:51:33>
  at CallbackQueue</CallbackQueue.prototype.drain  <__intern/node_modules/dojo/CallbackQueue.js:39:21>
  at nextTick</observer<  <__intern/node_modules/dojo/nextTick.js:52:21>
```

But when running the test via `node_modules/intern/client.html` I get the following output in DevTools:

```
AssertionError: expected [ 'alpha', 'bravo' ] to deeply equal [ Array(4) ]

  [
    0: "alpha",
    1: "bravo",
E   2: "charlie",
E   3: "delta",
E   length: 4
A   length: 2
  ]

 at Assertion.assertEql  <__intern/node_modules/chai/chai.js:765:10>
 at Assertion.ctx.(anonymous function) [as eql]  <__intern/node_modules/chai/chai.js:3475:25>
 at Assertion.assertEqual  <__intern/node_modules/chai/chai.js:731:19>
 at Assertion.ctx.(anonymous function) [as equal]  <__intern/node_modules/chai/chai.js:3475:25>
 at _expect  <test/unit/test-file.js:19:30>
 at Test.<test> [as test]  <test/unit/test-file.js:70:9>
 at <__intern/lib/Test.js:211:24>
 at <__intern/node_modules/dojo/Promise.js:156:41>
 at runCallbacks  <__intern/node_modules/dojo/Promise.js:19:22>
 at <__intern/node_modules/dojo/Promise.js:103:21>
```

Ignoring the (in this case rather useless) stack traces, this is the message I'd like to see in the Runner reporter as well:

```
AssertionError: expected [ 'alpha', 'bravo' ] to deeply equal [ Array(4) ]

  [
    0: "alpha",
    1: "bravo",
E   2: "charlie",
E   3: "delta",
E   length: 4
A   length: 2
  ]
```

Any idea where that array diff is swallowed so that I could try fixing this?

**Comment by jason0x43** [comment]
I'm sure about getting rid of the stack traces (they can be useful), but I agree that the tests coming from a remote browser should include diff information if it's available. I pushed an update to master that includes that information with test errors. If you'd like to leave out stack traces, one option would be to write a simple reporter that simply doesn't print stack traces with its error messages.

**Comment by rodneyrehm** [comment]
Agree about removing stack traces being a bad idea. If your fix already makes the diff show up in the Runner reporter, I guess we can close this. Thank You!
