### ISSUE TITLE
Safari tests crash with selenium > 2.48

### ISSUE THREAD

**Issue by chuwy** [theintern/intern#678]
I'm trying to update `selenium-version` to latest `2.53.1` and getting following error for Safari (tried Safari 6-9):

```
× safari 9.0 on OS X 10.11 - Helpers test - Add event listener (4.481s)
UnknownCommand: [POST http://(redacted)@localhost:4444/wd/hub/session/44f931eec2104340a9b88e90555ed91f/timeouts/implicit_wait / {"ms":5000}] Unknown command: setTimeout (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 2 milliseconds
Build info: version: '2.49.0', revision: '365eeb4', time: '2016-01-13 18:37:00'
System info: host: 'itako52211.prod.miso', ip: '172.20.52.211', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.6', java.version: '1.8.0_102'
Driver info: org.openqa.selenium.safari.SafariDriver
Capabilities [{browserName=safari, takesScreenshot=true, javascriptEnabled=true, version=9.1.2, cssSelectorsEnabled=true, platform=MAC, secureSsl=true}]
Session ID: null
at runRequest  <node_modules/leadfoot/Session.js:88:40>
at <node_modules/leadfoot/Session.js:109:39>
at new Promise  <node_modules/dojo/Promise.ts:411:3>
at ProxiedSession._post  <node_modules/leadfoot/Session.js:63:10>
at <node_modules/leadfoot/Session.js:508:18>
at <node_modules/dojo/Promise.ts:393:15>
at runCallbacks  <node_modules/dojo/Promise.ts:11:11>
at <node_modules/dojo/Promise.ts:317:4>
at run  <node_modules/dojo/Promise.ts:237:7>
at <node_modules/dojo/nextTick.ts:44:3>
at Command.target.(anonymous function) [as setFindTimeout]  <node_modules/leadfoot/Command.js:610:11>
at Test.Add event listener [as test]  <tests/functional/helpers.js:88:6>
at <node_modules/intern/lib/Test.js:181:24>
at <node_modules/intern/browser_modules/dojo/Promise.ts:393:15>
at runCallbacks  <node_modules/intern/browser_modules/dojo/Promise.ts:11:11>
at <node_modules/intern/browser_modules/dojo/Promise.ts:317:4>
at run  <node_modules/intern/browser_modules/dojo/Promise.ts:237:7>
at <node_modules/intern/browser_modules/dojo/nextTick.ts:44:3>
at _combinedTickCallback  <internal/process/next_tick.js:67:7>
at process._tickCallback  <internal/process/next_tick.js:98:9>
```

Here's test code:

```javascript
return this.remote
.get(require.toUrl('tests/pages/helpers.html'))
.setFindTimeout(5000)
.findByCssSelector('body.loaded')
.findById('click')
.click()
.getVisibleText()
.then(function (text){
assert.strictEqual(text, 'clicked', 'Add a click event listener');
});
```

It fails only for Safari with tests having `setFindTimeout`, all other browsers and tests without `setFindTimeout` work fine. Also Safari tests work fine for `selenium-version` <= 2.48. 

I'm using intern 3.3.1 with `SauceLabs` tunnel, here's config:

```javascript
define({
capabilities: {
'selenium-version': '2.53.1'
},
environments: [
{ browserName: 'internet explorer', version: '11', platform: 'Windows 8.1' },
{ browserName: 'safari', version: '9.0', platform: 'OS X 10.11' }
],
maxConcurrency: 1,
tunnel: 'SauceLabsTunnel',
excludeInstrumentation: /^(?:tests|node_modules)\//
});

```

Thanks.

**Comment by jason0x43** [comment]
Just to make sure, tests are fine with Selenium <= 2.48, but are broken with Selenium > 2.48?

**Comment by chuwy** [comment]
@jason0x43 yes, exactly.

**Comment by jason0x43** [comment]
Closing this as it's been overcome by events (Safari and Selenium have moved quite a ways past this)
