### ISSUE TITLE
Windows self tests: FAIL: intern/lib/reporters/JUnit - basic tests (6ms)

### ISSUE THREAD

**Issue by gitgrimbo** [theintern/intern#681]
Line ending issue.

Actual result is built using `\n`, Windows reads the expected result from disk using `\r\n` (perhaps dur to my Git line ending settings? I use `core.autocrlf=true`).

```
AssertionError: Report should match expected result: expected
'<?xml version="1.0" encoding="UTF-8" ?><testsuites><testsuite name="chrome 32 on Mac"failures="2" skipped="1" tests="5" time="1.234"><testsuite name="suite1" failures="2" skipped="1" tests="5" time="1.234"><testcase name="test1" time="0.045" status="0"/><testcase name="test2" time="0.045" status="1"><error message="Oops" type="Error">Error: Oops\n  at Test.basic tests ...</error></testcase><testcase name="test3" time="0.045" status="1"><failure message="Expected 1 + 1 to equal 3" type="AssertionError">AssertionError: Expected 1 + 1 to equal 3\n  at Test.basic tests ...</failure></testcase><testcase name="test4" time="0.045" status="0"><skipped>No time for that</skipped></testcase><testsuite name="suite5" failures="0" skipped="0" tests="1" time="0.045"><testcase name="test5.1" time="0.04" status="0"/></testsuite></testsuite></testsuite></testsuites>\n'
to equal
'<?xml version="1.0" encoding="UTF-8" ?><testsuites><testsuite name="chrome 32 on Mac"failures="2" skipped="1" tests="5" time="1.234"><testsuite name="suite1" failures="2" skipped="1" tests="5" time="1.234"><testcase name="test1" time="0.045" status="0"/><testcase name="test2" time="0.045" status="1"><error message="Oops" type="Error">Error: Oops\r\n  at Test.basic tests ...</error></testcase><testcase name="test3" time="0.045" status="1"><failure message="Expected 1 + 1 to equal 3" type="AssertionError">AssertionError: Expected 1 + 1 to equal 3\r\n  at Test.basic tests ...</failure></testcase><testcase name="test4" time="0.045" status="0"><skipped>No time for that</skipped></testcase><testsuite name="suite5" failures="0" skipped="0" tests="1" time="0.045"><testcase name="test5.1" time="0.04" status="0"/></testsuite></testsuite></testsuite></testsuites>\r\n'
  at Assertion.assertEqual  <node_modules\intern\node_modules\chai\chai.js:733:12>
  at Assertion.ctx.(anonymous function) [as equal]  <node_modules\intern\node_modules\chai\chai.js:3475:25>
  at Function.assert.strictEqual  <node_modules\intern\node_modules\chai\chai.js:2078:32>
  at Test.basic tests [as test]  <tests\unit\lib\reporters\JUnit.js:74:11>
  at <node_modules\intern\lib\Test.js:211:24>
  at <node_modules\intern\node_modules\dojo\Promise.ts:393:15>
  at runCallbacks  <node_modules\intern\node_modules\dojo\Promise.ts:11:11>
  at <node_modules\intern\node_modules\dojo\Promise.ts:317:4>
  at run  <node_modules\intern\node_modules\dojo\Promise.ts:237:7>
  at <node_modules\intern\node_modules\dojo\nextTick.ts:44:3>
```

The following line will fix in the test:

```js
	expected = expected.replace(/\r\n/g, "\n");
```

**Comment by jason0x43** [comment]
This is, as you suggest, likely due to the `autocrlf` setting. The report will always be generated with `\n`, but with `autocrlf=true`, the test comparison file will have its line endings converted to `\r\n`.
