### ISSUE TITLE
ECONNREFUSED while trying to connect with Sauce Labs Connect

### ISSUE THREAD

**Issue by jimothyhalpert7** [theintern/intern#687]
intern@3.3.2
node v6.5.0
Windows 7
Corporate proxy

After launching Sauce Labs Connect with `bin\sc -u username -k token`, we are able to launch a _Manual Test_ from the Sauce Labs webpage, and navigate to a resource, which is unavailable outside the corporate network.  We assume this means that _connect_ was able to set the correct proxy settings.

However, launching our test script with `node C:/project/node_modules/intern/runner.js config=tests/intern-sauceLabs` results in

```
Listening on 0.0.0.0:9000
Error: [GET https://saucelabs.com/rest/v1/info/platforms/webdriver] connect ECONNREFUSED 162.222.75.243:443
Error: connect ECONNREFUSED 162.222.75.243:443
at Object.exports._errnoException  <util.js:1026:11>
at exports._exceptionWithHostPort  <util.js:1049:20>
at TCPConnectWrap.afterConnect [as oncomplete]  <net.js:1081:14>
```

**Comment by sholladay** [comment]
So the [SauceLabsTunnel](https://github.com/theintern/digdug/blob/master/SauceLabsTunnel.js#L170) wasn't able to connect to saucelabs.com ... interesting. That REST API does not require authentication and so the only two simple explanations are:

 - SauceLabs had a hiccup / partial server outage.
 - Your firewall is blocking the outbound connection (possibly from Node, specifically, if it's a local software firewall).

Are you able to connect to https://saucelabs.com/rest/v1/info/platforms/webdriver using cURL or a browser _without_ your corporate proxy settings? Not talking about your private network resources here, just the public internet.

Assuming the answer is no, it might just be a [proxy configuration](https://theintern.github.io/digdug/module-digdug_Tunnel.html#proxy) issue. In which case, you should try specifying this in your Intern config:

```js
tunnelOptions : {
    proxy : 'hostname:port'
    // If the proxy needs authentication, then 'username:password@hostname:port'
}
```

**Comment by sholladay** [comment]
@jimothyhalpert7 did my advice above help at all?

**Comment by jason0x43** [comment]
Closing this due to inactivity
