### ISSUE TITLE
EADDRINUSE cannot be handled programmatically

### ISSUE THREAD

**Issue by vladikoff** [theintern/intern#868]
## Expected behavior

If intern throws `Error on EADDRINUSE` then promise should reject in `.run()` 

## Current behavior

No error thrown to `.run()`

## Steps to reproduce (for bugs)

Given programmatic usage:

```js
intern.configure(config);
try {
  intern.run().then(() => {
    console.log('good')
  }, (err) => {
    console.log('bad')
    console.log(err)

    process.exit(1);
  });
} catch (e) {
  process.exit(1);
}
```

## Environment

Intern version: 4.1.5
Node version: 6
NPM version: 2

## Additional information

**None of these breakpoints hit on EADDRINUSE:**

![image](https://user-images.githubusercontent.com/128755/34700047-c90dda9e-f4ae-11e7-9afa-4f70932d81a8.png)

Error:

```
Error: listen EADDRINUSE :::9090
  at Object.exports._errnoException  <util.js:1020:11>
  at exports._exceptionWithHostPort  <util.js:1043:20>
  at Server._listen2  <net.js:1258:14>
  at listen  <net.js:1294:10>
  at Server.listen  <net.js:1390:5>
  at <src/lib/Server.ts:154:42>
  at Server.start  <src/lib/Server.ts:67:9>
  at <src/lib/executors/Node.ts:348:7>
```

**Comment by vladikoff** [comment]
woooo awesome!!!!
