### ISSUE TITLE
Control click on html element does not propagate state of modifier keys

### ISSUE THREAD

**Issue by GARMBoshouwers** [theintern/intern#899]
## Expected behavior
When a html element is clicked, the onclick event handler should be supplied with any modifier keys (CTRL, ALT, SHFT) that were pressed during the click.

## Current behavior
When running the Intern script in Chrome, this seems to be working correctly. When running the same script in FireFox or Edge, the click is processed, but the modifier keys are not propagated to the javascript event handler.

## Steps to reproduce (for bugs)
Test HTML: https://pastebin.com/fmvN2L8d
Test script: https://pastebin.com/d3V93RmA

When the script runs in the Chrome browser, the test succeeds. When the test runs in either the FireFox or Edge browsers, this fails.

## Environment
Intern version: 4.1.5
Node version: 9.3.0
Chrome webdriver 2.36
Gecko webdriver 0.20 (32b)
Edge webdriver 16299

**Comment by GARMBoshouwers** [comment]
Has anyone had time to check this? Is there something I can provide that is missing?

This is still an issue in my running tests on selenium 3.4.0 as in the latest selenium version 3.11.0

**Comment by GARMBoshouwers** [comment]
Did you have a chance to check this bug out?

It blocks me from automatically testing our application in FireFox and Edge.

Is there anything I can provide that could help?

**Comment by GARMBoshouwers** [comment]
I tried this in newer versions, it is still an issue

Selenium 3.14.0
Intern version: 4.3.2
Node version: 9.3.0
Chrome webdriver 2.43
Gecko webdriver 0.23 (32b)
Edge webdriver 17134

**Comment by jason0x43** [comment]
I'll try to take a look at this in the next couple of days. @GARMBoshouwers Are you using Edge locally, or via a remote testing service?

**Comment by GARMBoshouwers** [comment]
These were all local tests.

**Comment by jason0x43** [comment]
Interesting... I've been having trouble lately getting Edge to work locally.

**Comment by GARMBoshouwers** [comment]
You mean getting MicrosoftWebDriver to run, or running tests in general? I needed a new webdriver and a windows update this morning, but after that it went ok, except for this issue.

Also, the Edge developer tools seemed to stop working after that windows update, so update at your own risk, I guess.

**Comment by GARMBoshouwers** [comment]
@jason0x43 Did you have any time to check this yet?

**Comment by GARMBoshouwers** [comment]
Another version update

Selenium 3.141.59
Intern version: 4.4.2
Node version: 9.3.0
Chrome webdriver 2.46
Gecko webdriver 0.24 (32b)
Edge webdriver (windows service)

Chrome still works and FireFox fails in the same way.

Edge seems to be completely broken. I first get an error about the coverage variables. I can circumvent those by disabling the coverage. But next it does not seem to accept the  session/{ID}/execute/sync call.
```
    UnknownCommand: [POST http://localhost:4444/wd/hub/session/CC6D62E9-4C37-488A-A003-0971FB39985C/execute/sync / {"script":"return (function simulateKeys(keys) {\n    var _a;\n    var target = document.activeElement;\n    function dispatch(kwArgs) {\n        var event;\n        if (typeof KeyboardEvent === 'function') {\n            event = new KeyboardEvent(kwArgs.type, {\n                bubbles: true,\n                cancelable: kwArgs.cancelable || false,\n                view: window,\n                key: kwArgs.key || '',\n                location: 3\n            });\n        }\n        else {\n            event = document.createEvent('KeyboardEvent');\n            event.initKeyboardEvent(kwArgs.type, true, kwArgs.cancelable || false, window, kwArgs.key || '', 3, '', 0, '');\n        }\n        return target.dispatchEvent(event);\n    }\n    function dispatchInput() {\n        var event;\n        if (typeof Event === 'function') {\n            event = new Event('input', { bubbles: true, cancelable: false });\n        }\n        else {\n            event = document.createEvent('Event');\n            event.initEvent('input', true, false);\n        }\n        return target.dispatchEvent(event);\n    }\n    keys = (_a = []).concat.apply(_a, keys.map(function (keys) { return keys.split(''); }));\n    for (var i = 0, j = keys.length; i < j; ++i) {\n        var key = keys[i];\n        var performDefault = true;\n        performDefault = dispatch({\n            type: 'keydown',\n            cancelable: true,\n            key: key\n        });\n        performDefault =\n            performDefault &&\n                dispatch({ type: 'keypress', cancelable: true, key: key });\n        if (performDefault) {\n            if ('value' in target) {\n                target.value =\n                    target.value.slice(0, target.selectionStart) +\n                        key +\n                        target.value.slice(target.selectionEnd);\n                dispatchInput();\n            }\n            else if (target.isContentEditable) {\n                var node = document.createTextNode(key);\n                var selection = window.getSelection();\n                var range = selection.getRangeAt(0);\n                range.deleteContents();\n                range.insertNode(node);\n                range.setStartAfter(node);\n                range.setEndAfter(node);\n                selection.removeAllRanges();\n                selection.addRange(range);\n            }\n        }\n        dispatch({ type: 'keyup', cancelable: true, key: key });\n    }\n}).apply(this, arguments);","args":[["","",""]]}] POST /session/CC6D62E9-4C37-488A-A003-0971FB39985C/execute/sync
    Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
    System info: host: 'MVGUITESTER', ip: '192.168.129.174', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_201'
    Driver info: driver.version: unknown
      at Server.post @ node_modules\src\Server.ts:361:16
      at runRequest @ node_modules\src\Session.ts:132:10
      at common_1.Task.cancelled @ node_modules\src\Session.ts:164:42
      at new e @ node_modules\@theintern\common\index.js:16:5076
      at InitializedProxiedSession.Session._delegateToServer @ node_modules\src\Session.ts:110:11
      at InitializedProxiedSession.Session.serverPost @ node_modules\src\Session.ts:174:16
      at InitializedProxiedSession.Session.execute @ node_modules\src\Session.ts:421:22
      at InitializedProxiedSession.Session.pressKeys @ node_modules\src\Session.ts:1384:18
      at sessionMethod @ node_modules\src\Command.ts:748:41
      at Command.<anonymous> @ node_modules\src\Command.ts:764:28
      at Command._callSessionMethod @ node_modules\src\Command.ts:733:11
      at Command.pressKeys @ node_modules\src\Command.ts:1170:16
      at Test.click div [as test] @ test.js:15:6
      @ src\lib\Test.ts:263:51
      @ node_modules\@theintern\common\index.js:16:7182
      @ anonymous
      at process._tickCallback @ internal\process\next_tick.js:160:7
```

**Comment by jason0x43** [comment]
What version of leadfoot are you running? (`npm ls @theintern/leadfoot`) Some issues cropped up with FF in the last couple of weeks, but those appeared to have been addressed with the latest Leadfoot release (2.2.7).

**Comment by jason0x43** [comment]
What version of Edge driver are you running?

**Comment by GARMBoshouwers** [comment]
I was using leadfoot 2.2.6. I tried a clean install of my node packages, which now includes leadfoot 2.2.8, with the same error.

For Edge I am think I am using the version installed as a windows service. The one installed using

```
DISM.exe /Online /Add-Capability /CapabilityName:Microsoft.WebDriver~~~~0.0.1.0
```

I'm not entirely sure it is found correctly, though. I don't get a 'driver not found' error, so I think it is found. I get this in the Selenium console:

```
2019-04-09 08:00:26.407:INFO::main: Logging initialized @559ms to org.seleniumhq.jetty9.util.log.StdErrLog
08:00:26.641 INFO [WebDriverServlet.<init>] - Initialising WebDriverServlet
08:00:26.782 INFO [SeleniumServer.boot] - Selenium Server is up and running on port 4444
08:00:35.449 INFO [ActiveSessionFactory.apply] - Capabilities are: {
  "browserName": "MicrosoftEdge",
  "idle-timeout": 60,
  "name": "intern"
}
08:00:35.449 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.selenium.grid.session.remote.ServicedSession$Factory (provider: org.openqa.selenium.edge.EdgeDriverService)
[08:00:35.527] - Listening on http://127.0.0.1:48537/
[08:00:35.527] - Listening on http://[::1]:48537/
08:00:36.777 INFO [ProtocolHandshake.createSession] - Detected dialect: W3C
08:00:36.808 INFO [RemoteSession$Factory.lambda$performHandshake$0] - Started new session 3E232F9E-74AE-4777-8730-E288BCB488F7 (org.openqa.selenium.edge.EdgeDriverService)
08:00:37.124 INFO [ActiveSessions$1.onStop] - Removing session 3E232F9E-74AE-4777-8730-E288BCB488F7 (org.openqa.selenium.edge.EdgeDriverService)
The following JSON wire protocol command endpoint is not allowed when server is running in W3C mode.
GET /shutdown
```

The version the Edge driver install command returns is:
Version: 10.0.17763.1
Image Version: 10.0.17763.379

**Comment by GARMBoshouwers** [comment]
I tested this bug in Intern 4.8.0 and I noticed something strange.

The .moveMouseTo offset coordinates do not seem to work correctly in Chrome and EdgeChromium. According to the documentation, the offset should be relative to the Top Left corner of the provided element. But here, they seem to be relative to the middle of the element.

Firefox seems to use the offsets in the manner described in the documentation. All three browsers still fail to use the provided modifier keys.

Intern: 4.8.0.
Selenium: 3.141.59
chromedriver: 79.0.3945.36
msedgedriver: 79.0.309.15
geckodriver: 0.26.0
