### ISSUE TITLE
Intern does not terminate gracefully when functional test file is missing

### ISSUE THREAD

**Issue by gitgrimbo** [theintern/intern#925]
## Expected behavior
Intern terminates gracefully.

## Current behavior
Intern hangs (does not pass control of the terminal back to the user).

## Steps to reproduce (for bugs)

Pass non-existent functional test to the command line:

`npx intern config=@all reporters=simple suites= functionalSuites=a`

Intern hangs after printing the following:

```
DEBUG: 'failed to load resource (D:/dev/git_repos/harviewer2/a.js)'
DEBUG: { Error: ENOENT: no such file or directory, open 'D:/dev/git_repos/harviewer2/a.js'
    at Object.fs.openSync (fs.js:577:3)
    at Object.fs.readFileSync (fs.js:483:33)
    at Function.injectUrl (D:\dev\git_repos\harviewer2\node_modules\dojo\_base\configNode.js:91:29)
    at injectModule (D:\dev\git_repos\harviewer2\node_modules\dojo\dojo.js:1580:9)
    at forEach (D:\dev\git_repos\harviewer2\node_modules\dojo\dojo.js:112:6)
    at D:\dev\git_repos\harviewer2\node_modules\dojo\dojo.js:786:5
    at guardCheckComplete (D:\dev\git_repos\harviewer2\node_modules\dojo\dojo.js:1307:5)
    at injectDependencies (D:\dev\git_repos\harviewer2\node_modules\dojo\dojo.js:785:4)
    at contextRequire (D:\dev\git_repos\harviewer2\node_modules\dojo\dojo.js:849:6)
    at req (D:\dev\git_repos\harviewer2\node_modules\dojo\dojo.js:143:11)
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'D:/dev/git_repos/harviewer2/a.js' }
(node:1504) [DEP0028] DeprecationWarning: util.debug is deprecated. Use console.error instead.
```

## Environment
Intern version: 4.2.0
Node version: 10.3.0
NPM version: 6.1.0
Browser version: N/A

**Comment by jason0x43** [comment]
It seems like the `dojo` loader might be involved here, because the default (node) loader exits with an error, as expected.

**Comment by jason0x43** [comment]
Finally getting a chance to look at this... The problem is definitely specific to the dojo1 loader; the dojo2 and Node loaders don't exhibit the issue.
