### ISSUE TITLE
Istanbul emitting metrics.isEmpty error for some projects

### ISSUE THREAD

**Issue by jason0x43** [theintern/intern#939]
Intern 4.2.2, which uses Istanbul-reports 1.3.x.

```
TypeError: metrics.isEmpty is not a function
  at tableRow  <node_modules\intern\node_modules\istanbul-reports\lib\text\index.js:133:27>
  at TextReport.onSummary  <node_modules\intern\node_modules\istanbul-reports\lib\text\index.js:188:15>
  at Visitor.(anonymous function) [as onSummary]  <node_modules\istanbul-lib-report\lib\tree.js:34:30>
  at ReportNode.Node.visit  <node_modules\istanbul-lib-report\lib\tree.js:121:17>
  at Tree.visit  <node_modules\istanbul-lib-report\lib\tree.js:158:20>
  at Runner.Coverage.createCoverageReport  <src\lib\reporters\Coverage.ts:65:7>
  at Runner.runEnd  <src\lib\reporters\Runner.ts:159:8>
  at <src\lib\reporters\Reporter.ts:94:31>
  at <src\lib\executors\Executor.ts:300:30>
  at <node_modules\@dojo\core\async\Task.ts:351:12>
```

See https://github.com/gotwarlost/istanbul/issues/868

**Comment by gitgrimbo** [comment]
I'm also seeing this with 4.2.0.

**Comment by jason0x43** [comment]
This is fixed via dependency updates.
