### ISSUE TITLE
{pwd} Not Working on Windows

### ISSUE THREAD

**Issue by nicknisi** [theintern/intern#943]
## Expected behavior

Intern to be able to correctly parse `{pwd}` on Windows.

## Current behavior

Using configuration like the following:

```json
  "environments": {
    "browserName": "chrome",
    "fixSessionCapabilities": false,
    "chromeOptions": {
      "binary": "{pwd}/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron",
      "args": ["app={pwd}/build/bootstrap.js"] 
    }
  },
```

We get the following errors.

```
SyntaxError: Unexpected token e in JSON at position 315
    at JSON.parse (<anonymous>)
    at parseJson (C:\Users\IEUser\code\intern-examples\electron-example\node_modules\intern\lib\common\util.js:186:21)
    at C:\Users\IEUser\code\intern-examples\electron-example\node_modules\intern\lib\common\util.js:40:26
    at C:\Users\IEUser\code\intern-examples\electron-example\node_modules\@dojo\core\async\Task.js:220:28
    at handler (C:\Users\IEUser\code\intern-examples\electron-example\node_modules\@dojo\core\async\ExtensiblePromise.js:126:37)
    at <anonymous>
npm ERR! Test failed.  See above for more details.
```

## Possible solution

This seems to be caused by the use of both `/` and `\` in in the path, leading to some characters being escaped.

## Steps to reproduce (for bugs)

1. Clone the intern electron example at https://github.com/theintern/intern-examples/tree/master/electron-example
2. `npm i`
3. `npm run build`
4. `npm test`

## Environment

This is easily tested with  the electron example on Windows

Intern version: 4
Node version: 8
NPM version: 5
Browser version: Chrome

**Comment by jason0x43** [comment]
Hmmm...problem #1: `npm run build` doesn't even work on windows because it uses `cp`.

**Comment by jason0x43** [comment]
Interesting. I guess node in git bash still comes back with Windows-style paths, then? (Not terribly relevant, just curious)
