### ISSUE TITLE
NoSuchDriver crashes with Firefox

### ISSUE THREAD

**Issue by vladikoff** [theintern/intern#992]
We are experiencing Firefox crashes in CI and WSL (Windows) environment, (due to excessive memory?).  Related issue from before: https://github.com/theintern/intern/issues/967

## Expected behavior

No crashes with `NoSuchDriver` or more error information.

## Current behavior

Crashes with the following:

```
Suite firefox on linux 4.15.0-1043-aws - reset_password FAILED
NoSuchDriver: [GET http://localhost:4444/wd/hub/session/12f27397-9792-4b31-88d6-3a8d727114e4/screenshot] Tried to run command without establishing a connection
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: '1f26db72d236', ip: '172.31.0.3', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-1043-aws', java.version: '11.0.4'
Driver info: driver.version: unknown
  at Command.<anonymous>  <tests/functional/lib/helpers.js:92:24>
  at Command.<anonymous>  <tests/functional/lib/helpers.js:73:18>
  at Command.<anonymous>  <tests/functional/lib/helpers.js:68:10>
  at Suite.beforeEach  <tests/functional/reset_password.js:117:8>
  at <src/lib/Suite.ts:383:26>
  at runLifecycleMethod  <src/lib/Suite.ts:351:13>
  at next  <src/lib/Suite.ts:522:32>
```

## Possible solution

Clear Firefox memory via `about:memory`

## Environment

Intern version: 4.4.3
Node version: 10 / 12
NPM version: 6
Browser version: Firefox 68

## Additional information

Ref: https://github.com/mozilla/fxa/issues/1982
Ref: https://github.com/mozilla/fxa/pull/1996/files

**Comment by jason0x43** [comment]
Hmmm...that error makes it look like geckodriver died at some point.

Do you happen to have a testcase that can reproduce the error? I haven't seen any recent CI Firefox-related failures with Intern itself, and after running some simple testcases on Windows with FF 68 and Intern 4.4.3 (leadfoot 2.2.12) nothing's jumping out at me. Was this happening with FF 67?

The previous issue was due to an infinite loop in one of the feature tests that came up when a Firefox response changed in a new version, and it would fail pretty consistently. The current issue doesn't seem to be as obvious, unfortunately.

**Comment by vladikoff** [comment]
> as this happening with FF 67?

In 68 and 57. Once we added the memory clean step then it stopped :O
