### ISSUE TITLE
Suite chrome on any platform FAILED

### ISSUE THREAD

**Issue by mostafa-raafat** [theintern/intern#997]
## when i run npm run test on dojo 1 example test run on node but failed on browser [chrome, firefox , ie]

```
✓ node - SimpleTodoModel - default data (0.001s)
✓ node - SimpleTodoModel - get incomplete (empty model) (0s)
✓ node - SimpleTodoModel - get complete (empty model) (0s)
No unit test coverage for node
node: 3 passed, 0 failed
Suite chrome on any platform FAILED
JavaScriptError: [POST http://localhost:4444/wd/hub/session/398c1230790e57840525774b42fce3d7/execute / {"script":"return (function getCoverageData(coverageVariable) {\n        var coverageData = (function () {\n            return this;\n        })()[coverageVariable];\n        return coverageData && JSON.stringify(coverageData);\n    }).apply(this, arguments);","args":["__coverage__"]}] unknown error:
call function result missing 'value'
  (Session info: chrome=78.0.3904.108)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 10.0.17763 x86_64)
  at Server.post  <node_modules\src\Server.ts:367:14>
  at runRequest  <node_modules\src\Session.ts:132:33>
  at <node_modules\src\Session.ts:164:38>
  at new Task  <node_modules\@dojo\core\async\Task.ts:239:3>
  at InitializedProxiedSession.Session._delegateToServer  <node_modules\src\Session.ts:110:9>
  at InitializedProxiedSession.Session.serverPost  <node_modules\src\Session.ts:174:14>
  at InitializedProxiedSession.Session.execute  <node_modules\src\Session.ts:368:20>
  at <src\lib\ProxiedSession.ts:143:16>
  at <node_modules\@dojo\core\async\Task.ts:351:12>
  at handler  <node_modules\@dojo\core\async\ExtensiblePromise.ts:229:14>
(ノಠ益ಠ)ノ彡┻━┻
JavaScriptError: [POST http://localhost:4444/wd/hub/session/398c1230790e57840525774b42fce3d7/execute / {"script":"return (function getCoverageData(coverageVariable) {\n        var coverageData = (function () {\n            return this;\n        })()[coverageVariable];\n        return coverageData && JSON.stringify(coverageData);\n    }).apply(this, arguments);","args":["__coverage__"]}] unknown error:
call function result missing 'value'
  (Session info: chrome=78.0.3904.108)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 10.0.17763 x86_64)
  at Server.post  <node_modules\src\Server.ts:367:14>
  at runRequest  <node_modules\src\Session.ts:132:33>
  at <node_modules\src\Session.ts:164:38>
  at new Task  <node_modules\@dojo\core\async\Task.ts:239:3>
  at InitializedProxiedSession.Session._delegateToServer  <node_modules\src\Session.ts:110:9>
  at InitializedProxiedSession.Session.serverPost  <node_modules\src\Session.ts:174:14>
  at InitializedProxiedSession.Session.execute  <node_modules\src\Session.ts:368:20>
  at <src\lib\ProxiedSession.ts:143:16>
  at <node_modules\@dojo\core\async\Task.ts:351:12>
  at handler  <node_modules\@dojo\core\async\ExtensiblePromise.ts:229:14>

TOTAL: tested 1 platforms, 3 passed, 0 failed; fatal error occurred
```

## Environment

Intern version: 4.1.0
Node version: v12.13.0
NPM version: 6.12.0
Browser version: chrome 78.0.3904.108

**Comment by jason0x43** [comment]
Do you see the problem with more recent versions of Intern? (Latest is 4.6.0)

**Comment by amrtn** [comment]
I was experiencing the same issue with the stock sample project. After updating it to the last intern version (4.8.0) the test works as expected.

**Comment by jason0x43** [comment]
Closing this in favor of https://github.com/theintern/intern-examples/issues/56 as the issue appears to be an outdated version of Intern used in the examples.
